name: "Notify Status"
description: "Sends notifications to GitHub PR comments and Google Chat."
inputs:
  github_token:
    description: "GitHub Token for API access"
    required: true
  pr_number:
    description: "Pull Request number to comment on"
    required: false
  repo:
    description: "Repository owner/name"
    required: false
    default: ${{ github.repository }}
  webhook_url:
    description: "Google Chat Webhook URL"
    required: false
  pr_message:
    description: "Message to post on PR"
    required: false
  chat_message:
    description: "Message to post on Google Chat (defaults to pr_message if empty)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Notify
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        PR_NUMBER: ${{ inputs.pr_number }}
        REPO: ${{ inputs.repo }}
        WEBHOOK_URL: ${{ inputs.webhook_url }}
        PR_MSG: ${{ inputs.pr_message }}
        CHAT_MSG: ${{ inputs.chat_message }}
      run: |
        # 1. Notify GitHub PR using jq for safe JSON encoding
        if [ -n "$PR_NUMBER" ] && [ -n "$PR_MSG" ]; then
          echo "Commenting on PR #$PR_NUMBER..."

          # Use jq for safe JSON encoding
          json_payload=$(jq -n --arg body "$PR_MSG" '{body: $body}')

          response=$(curl -s -w "%{http_code}" --max-time 30 \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -X POST \
            -d "$json_payload" \
            "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments")

          http_code="${response: -3}"
          if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 300 ]; then
            echo "PR comment posted successfully"
          else
            echo "::warning::Failed to post PR comment (HTTP $http_code)"
          fi
        fi

        # 2. Notify Google Chat
        if [ -n "$WEBHOOK_URL" ]; then
          MSG="${CHAT_MSG:-$PR_MSG}"
          if [ -n "$MSG" ]; then
            echo "Sending Google Chat notification..."

            json_payload=$(jq -n --arg text "$MSG" '{text: $text}')

            if ! curl -s --max-time 30 \
                 -H "Content-Type: application/json" \
                 -d "$json_payload" \
                 "$WEBHOOK_URL" > /dev/null; then
              echo "::warning::Failed to send Google Chat notification"
            fi
          fi
        fi

