name: "Docker Build & Push"
description: "Builds and pushes a Docker image to a registry with optional layer caching"
inputs:
  image_full_name:
    description: "Full image name including registry and tag"
    required: true
  build_args:
    description: "Additional docker build arguments (e.g., --build-arg KEY=value)"
    required: false
    default: ""
  context:
    description: "Build context path"
    required: false
    default: "."
  cache_enabled:
    description: "Enable Docker layer caching using BuildKit"
    required: false
    default: "false"
  cache_image:
    description: "Cache image reference. If empty, derives from image_full_name with :buildcache tag"
    required: false
    default: ""

outputs:
  status:
    description: "Result status (success, build_failed)"
    value: ${{ steps.result.outputs.status }}

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Prepare Build Args
      id: prepare
      shell: bash
      env:
        BUILD_ARGS: ${{ inputs.build_args }}
        IMAGE: ${{ inputs.image_full_name }}
        CACHE_IMAGE: ${{ inputs.cache_image }}
      run: |
        # Convert build_args to KEY=value format (remove --build-arg prefix if present)
        # and expand environment variables
        CLEAN_ARGS=$(echo "$BUILD_ARGS" | sed 's/--build-arg //g' | envsubst)
        echo "build_args<<EOF" >> "$GITHUB_OUTPUT"
        echo "$CLEAN_ARGS" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

        # Derive cache image if not specified
        if [ -z "$CACHE_IMAGE" ]; then
          # Remove the tag from the image to use as cache base
          CACHE_IMAGE="${IMAGE%:*}:buildcache"
        fi
        echo "cache_image=$CACHE_IMAGE" >> "$GITHUB_OUTPUT"

    - name: Build and Push
      id: build-push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ inputs.image_full_name }}
        build-args: ${{ steps.prepare.outputs.build_args }}
        cache-from: ${{ inputs.cache_enabled == 'true' && format('type=registry,ref={0}', steps.prepare.outputs.cache_image) || '' }}
        cache-to: ${{ inputs.cache_enabled == 'true' && format('type=registry,ref={0},mode=max', steps.prepare.outputs.cache_image) || '' }}

    - name: Set Final Status
      id: result
      if: always()
      shell: bash
      run: |
        if [ "${{ steps.build-push.outcome }}" = "success" ]; then
          echo "status=success" >> "$GITHUB_OUTPUT"
        else
          echo "status=build_failed" >> "$GITHUB_OUTPUT"
        fi
