name: "Docker Build & Push"
description: "Builds and pushes a Docker image to a registry"
inputs:
  image_full_name:
    description: "Full image name including registry and tag"
    required: true
  build_args:
    description: "Additional docker build arguments (e.g., --build-arg KEY=value)"
    required: false
    default: ""
  context:
    description: "Build context path"
    required: false
    default: "."

outputs:
  status:
    description: "Result status (success, build_failed, push_failed)"
    value: ${{ steps.result.outputs.status }}

runs:
  using: "composite"
  steps:
    - name: Build
      id: build
      shell: bash
      env:
        IMAGE: ${{ inputs.image_full_name }}
        BUILD_ARGS: ${{ inputs.build_args }}
        BUILD_CTX: ${{ inputs.context }}
      run: |
        echo "Building $IMAGE..."

        # Build command array safely (no eval)
        build_cmd=(docker build -t "$IMAGE")

        # Add build args if provided
        if [ -n "$BUILD_ARGS" ]; then
          # Read args line by line, expanding env vars safely
          while IFS= read -r arg || [ -n "$arg" ]; do
            arg=$(echo "$arg" | xargs)  # trim whitespace
            [ -z "$arg" ] && continue
            # Expand environment variables using envsubst
            expanded_arg=$(echo "$arg" | envsubst)
            build_cmd+=($expanded_arg)
          done <<< "$BUILD_ARGS"
        fi

        build_cmd+=("$BUILD_CTX")

        echo "Running: ${build_cmd[*]}"
        if "${build_cmd[@]}"; then
          echo "status=build_success" >> "$GITHUB_OUTPUT"
        else
          echo "::error::Docker build failed"
          echo "status=build_failed" >> "$GITHUB_OUTPUT"
        fi

    - name: Push
      if: steps.build.outputs.status == 'build_success'
      id: push
      shell: bash
      env:
        IMAGE: ${{ inputs.image_full_name }}
      run: |
        echo "Pushing $IMAGE..."
        if docker push "$IMAGE"; then
          echo "status=push_success" >> "$GITHUB_OUTPUT"
        else
          echo "::error::Docker push failed"
          echo "status=push_failed" >> "$GITHUB_OUTPUT"
        fi

    - name: Set Final Status
      id: result
      if: always()
      shell: bash
      env:
        BUILD_STATUS: ${{ steps.build.outputs.status }}
        PUSH_STATUS: ${{ steps.push.outputs.status }}
      run: |
        if [ "$PUSH_STATUS" = "push_success" ]; then
          echo "status=success" >> "$GITHUB_OUTPUT"
        elif [ "$PUSH_STATUS" = "push_failed" ]; then
          echo "status=push_failed" >> "$GITHUB_OUTPUT"
        elif [ "$BUILD_STATUS" = "build_failed" ]; then
          echo "status=build_failed" >> "$GITHUB_OUTPUT"
        else
          echo "status=unknown" >> "$GITHUB_OUTPUT"
        fi
