name: "K8s Rollout Restart"
description: "Restarts a Kubernetes deployment and waits for rollout status"
inputs:
  deployment_name:
    description: "Deployment name"
    required: true
  namespace:
    description: "Namespace"
    required: false
    default: "default"

outputs:
  success:
    description: "true if successful"
    value: ${{ steps.restart.outputs.success }}

runs:
  using: "composite"
  steps:
    - name: Restart
      id: restart
      shell: bash
      env:
        DEPLOYMENT: ${{ inputs.deployment_name }}
        NS: ${{ inputs.namespace }}
      run: |
        set -euo pipefail
        echo "🔄 Reiniciando deployment '$DEPLOYMENT' en namespace '$NS'..."
        kubectl rollout restart deployment/"$DEPLOYMENT" -n "$NS"
        kubectl rollout status deployment/"$DEPLOYMENT" -n "$NS"
        echo "✅ Reinicio completado."
        echo "success=true" >> "$GITHUB_OUTPUT"

