name: "Determine Build Context"
description: "Determines branch, tag, and status for Docker builds based on event type"
inputs:
  event_name:
    description: "GitHub event name (issue_comment or release)"
    required: true
  is_valid_command:
    description: "Result from parse-comment (true/false)"
    required: false
    default: "false"
  parsed_branch:
    description: "Branch parsed from comment"
    required: false
  parsed_tag:
    description: "Tag parsed from comment"
    required: false
  github_token:
    description: "GitHub token for API calls"
    required: true
  allowed_tags:
    description: "Comma-separated list of additional allowed tags (case-insensitive, e.g., 'DEV,dev'). Use 'SEMVER' to allow semantic versioning on DEV branch (e.g., 'DEV,SEMVER'). Semver is always allowed on main branch."
    required: false
    default: ""

outputs:
  branch:
    description: "The actual git branch to checkout"
    value: ${{ steps.ctx.outputs.branch }}
  safe_branch:
    description: "Branch name safe for docker tags (slashes replaced)"
    value: ${{ steps.ctx.outputs.safe_branch }}
  tag:
    description: "The final docker tag to use"
    value: ${{ steps.ctx.outputs.tag }}
  status:
    description: "Logical status (e.g., invalid_tag_main, success, etc.)"
    value: ${{ steps.ctx.outputs.status }}
  job_url:
    description: "URL to the workflow run"
    value: ${{ steps.ctx.outputs.job_url }}

runs:
  using: "composite"
  steps:
    - name: Determine
      id: ctx
      shell: bash
      env:
        EVENT: ${{ inputs.event_name }}
        IS_VALID: ${{ inputs.is_valid_command }}
        PR_BRANCH: ${{ inputs.parsed_branch }}
        PR_TAG: ${{ inputs.parsed_tag }}
        GH_TOKEN: ${{ inputs.github_token }}
        ALLOWED_TAGS: ${{ inputs.allowed_tags }}
      run: |
        TAG=""
        BRANCH=""
        SAFE_BRANCH=""
        LOGICAL_STATUS=""
        JOB_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

        if [[ "$EVENT" == "issue_comment" ]]; then
           if [[ "$IS_VALID" != "true" ]]; then
              echo "status=not_build_command" >> "$GITHUB_OUTPUT"
              exit 0
           fi

           BRANCH="$PR_BRANCH"
           if [[ -z "$BRANCH" ]]; then
             # Try to fetch branch from PR API (if comment is on a PR)
             PR_URL=$(jq -r '.issue.pull_request.url // empty' < "$GITHUB_EVENT_PATH")
             if [ -n "$PR_URL" ]; then
               BRANCH=$(curl -s --max-time 30 -H "Authorization: token $GH_TOKEN" "$PR_URL" | jq -r '.head.ref // empty')
             fi
           fi

           # If still no branch (issue comment without -b flag), use default branch
           if [ -z "$BRANCH" ] || [ "$BRANCH" == "null" ]; then
             # Check if this is a PR or an issue
             IS_PR=$(jq -r '.issue.pull_request // empty' < "$GITHUB_EVENT_PATH")
             if [ -z "$IS_PR" ]; then
               # This is an issue comment, branch must be specified with -b flag
               echo "::error::Branch must be specified with -b flag for issue comments (e.g., 'build -b main')"
               echo "status=error_branch_required" >> "$GITHUB_OUTPUT"
               exit 0
             else
               echo "::error::Could not determine branch from PR"
               echo "status=error_branch_unknown" >> "$GITHUB_OUTPUT"
               exit 0
             fi
           fi
           
           SAFE_BRANCH=$(echo "$BRANCH" | tr '/' '-')
           TAG="${PR_TAG:-$SAFE_BRANCH}"
           
           # Validation logic
           is_semver() { [[ "$1" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; }

           # Check if SEMVER is allowed for current branch
           # SEMVER is allowed on main (always) and DEV branch (when SEMVER in allowed_tags)
           is_semver_allowed() {
             # Always allow semver on main branch
             if [[ "$BRANCH" == "main" ]]; then
               return 0
             fi

             # For DEV branch, check if SEMVER is in allowed_tags
             local branch_upper=$(echo "$BRANCH" | tr '[:lower:]' '[:upper:]')
             if [[ "$branch_upper" == "DEV" ]]; then
               if [[ -n "$ALLOWED_TAGS" ]]; then
                 local allowed_upper=$(echo "$ALLOWED_TAGS" | tr '[:lower:]' '[:upper:]')
                 [[ "$allowed_upper" =~ (^|,)SEMVER(,|$) ]] && return 0
               fi
             fi

             return 1
           }

           # Check if tag is in allowed list (case-insensitive)
           is_allowed_tag() {
             local tag_upper=$(echo "$1" | tr '[:lower:]' '[:upper:]')
             # Always allow MAIN/main
             if [[ "$tag_upper" == "MAIN" ]]; then return 0; fi
             # Check additional allowed tags
             if [[ -n "$ALLOWED_TAGS" ]]; then
               IFS=',' read -ra TAGS <<< "$ALLOWED_TAGS"
               for allowed_tag in "${TAGS[@]}"; do
                 allowed_tag_upper=$(echo "$allowed_tag" | tr '[:lower:]' '[:upper:]' | xargs)
                 if [[ "$tag_upper" == "$allowed_tag_upper" ]]; then return 0; fi
               done
             fi
             return 1
           }

           if [[ "$BRANCH" == "main" && -n "$PR_TAG" ]]; then
             # If tag is "main" (case-insensitive), allow it
             PR_TAG_UPPER=$(echo "$PR_TAG" | tr '[:lower:]' '[:upper:]')
             if [[ "$PR_TAG_UPPER" != "MAIN" ]]; then
               # For other tags, must be semver or in allowed list
               if ! is_allowed_tag "$PR_TAG" && ! is_semver "$PR_TAG"; then
                 LOGICAL_STATUS="invalid_tag_main"
               fi
             fi
           elif [[ "$BRANCH" != "main" && -n "$PR_TAG" ]]; then
             # For non-main branches, only restrict semver tags
             # Semver tags require explicit permission (SEMVER in allowed_tags for DEV branch)
             # Non-semver tags are always allowed (branch names, feature tags, etc.)
             if is_semver "$PR_TAG"; then
               if ! is_semver_allowed && ! is_allowed_tag "$PR_TAG"; then
                 LOGICAL_STATUS="invalid_tag_branch"
               fi
             fi
           fi

        elif [[ "$EVENT" == "release" ]]; then
           TAG="${{ github.event.release.tag_name }}"
           BRANCH="${{ github.event.release.target_commitish }}"
           if [[ "$BRANCH" != "main" ]]; then LOGICAL_STATUS="invalid_release_branch"; fi
        else
           LOGICAL_STATUS="not_supported_event"
        fi

        echo "branch=$BRANCH" >> "$GITHUB_OUTPUT"
        echo "safe_branch=$SAFE_BRANCH" >> "$GITHUB_OUTPUT"
        echo "tag=$TAG" >> "$GITHUB_OUTPUT"
        echo "job_url=$JOB_URL" >> "$GITHUB_OUTPUT"
        echo "status=$LOGICAL_STATUS" >> "$GITHUB_OUTPUT"

