name: "GCP Docker Build & Push (No GitOps)"
description: |
  Builds and pushes Docker images to GCP Artifact Registry without GitOps integration or GitHub artifact repository authentication.
  Suitable for frontends and standalone microservices. Supports PR comments and issue comments (use 'build -b <branch>' for issues).

  REQUIRED WORKFLOW PERMISSIONS for issue_comment trigger:
    permissions:
      contents: read
      issues: write
      pull-requests: write
      id-token: write
inputs:
  workload_identity_provider:
    description: "GCP Workload Identity Provider resource name"
    required: true
  service_account:
    description: "GCP Service Account email"
    required: true
  google_chat_webhook:
    description: "Google Chat Webhook URL for notifications"
    required: false
  cache_enabled:
    description: "Enable Docker layer caching (uses GCP Artifact Registry)"
    required: false
    default: "false"

  # GitOps Configuration (optional - for semantic versioning releases to production)
  gitops_repo:
    description: "GitOps repository name (e.g., 'Automya/gitops')"
    required: false
  prod_manifest_path:
    description: "Path to production manifest in GitOps repo"
    required: false
  gitops_token:
    description: "GitHub token with access to GitOps repository"
    required: false
  container_name:
    description: "Container name in Kubernetes deployment"
    required: false

runs:
  using: "composite"
  steps:
    - name: Build and Push
      uses: Automya/CI-CD-template/actions/build-image-docker@main
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}
        google_chat_webhook: ${{ inputs.google_chat_webhook }}
        cache_enabled: ${{ inputs.cache_enabled }}
        gitops_repo: ${{ inputs.gitops_repo }}
        prod_manifest_path: ${{ inputs.prod_manifest_path }}
        gitops_token: ${{ inputs.gitops_token }}
        container_name: ${{ inputs.container_name }}
