name: "GCP Docker Build & Push (No GitOps)"
description: "Builds and pushes Docker images to GCP Artifact Registry without GitOps integration or GitHub artifact repository authentication. Suitable for frontends and standalone microservices."
inputs:
  workload_identity_provider:
    description: "GCP Workload Identity Provider resource name"
    required: true
  service_account:
    description: "GCP Service Account email"
    required: true
  google_chat_webhook:
    description: "Google Chat Webhook URL for notifications"
    required: false

runs:
  using: "composite"
  steps:
    - name: Build and Push
      uses: Automya/CI-CD-template/actions/build-image-docker@main
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}
        google_chat_webhook: ${{ inputs.google_chat_webhook }}
