name: Sync Config to GitOps
description: >
  Syncs a local file (e.g., application.yml) to a ConfigMap in a GitOps repository.
  Triggered by a PR comment: `sync -b <branch> -e <env>`.

inputs:
  staging_source_file:
    description: 'Path to the local source file for Staging.'
    required: true
  prod_source_file:
    description: 'Path to the local source file for Production.'
    required: true
  staging_configmap:
    description: 'Path to the Staging ConfigMap YAML file in the GitOps repository.'
    required: true
  prod_configmap:
    description: 'Path to the Prod ConfigMap YAML file in the GitOps repository.'
    required: true
  gitops_repo:
    description: 'GitOps repository in format owner/repo.'
    required: true
  github_token:
    description: 'Token with write permissions to the GitOps repo.'
    required: true
  source_repo_token:
    description: 'Token to comment in the source PR.'
    required: false
    default: ''
  branch:
    description: 'Base branch in the GitOps repo (default: main).'
    required: false
    default: 'main'
  configmap_key:
    description: 'Key in the ConfigMap data to update.'
    required: false
    default: 'application.yml'
  commit_message:
    description: 'Commit message.'
    required: false
    default: 'chore: update application.yml config'

runs:
  using: composite
  steps:
    - name: Initialize
      shell: bash
      run: |
        if [ -n "${{ inputs.source_repo_token }}" ]; then
          echo "COMMENT_TOKEN=${{ inputs.source_repo_token }}" >> $GITHUB_ENV
        else
          echo "COMMENT_TOKEN=${{ inputs.github_token }}" >> $GITHUB_ENV
        fi

    - name: Parse Sync Command
      id: parse
      uses: ./actions/parse-comment
      with:
        comment_body: ${{ github.event.comment.body }}
        command_prefix: "sync"

    - name: Validate & Setup Context
      if: steps.parse.outputs.is_valid == 'true'
      shell: bash
      env:
        SYNC_BRANCH: ${{ steps.parse.outputs.branch }}
        ENV_RAW: ${{ steps.parse.outputs.env }}
      run: |
        if [ -z "$SYNC_BRANCH" ] || [ -z "$ENV_RAW" ]; then
           echo "SKIP=true" >> $GITHUB_ENV
           exit 0
        fi

        ENV_LOWER=$(echo "$ENV_RAW" | tr '[:upper:]' '[:lower:]')
        case "$ENV_LOWER" in
          staging|stage|st|stag|stg)
            TARGET_ENV="staging"
            TARGET_CONFIGMAP="${{ inputs.staging_configmap }}"
            SOURCE_FILE_PATH="${{ inputs.staging_source_file }}"
            ;;
          prod|production|prd)
            TARGET_ENV="prod"
            TARGET_CONFIGMAP="${{ inputs.prod_configmap }}"
            SOURCE_FILE_PATH="${{ inputs.prod_source_file }}"
            ;;
          *)
            echo "Error: Entorno no soportado: $ENV_RAW"
            exit 1
            ;;
        esac

        echo "SYNC_BRANCH=$SYNC_BRANCH" >> $GITHUB_ENV
        echo "TARGET_ENV=$TARGET_ENV" >> $GITHUB_ENV
        echo "TARGET_CONFIGMAP=$TARGET_CONFIGMAP" >> $GITHUB_ENV
        echo "SOURCE_FILE_PATH=$SOURCE_FILE_PATH" >> $GITHUB_ENV
        echo "SKIP=false" >> $GITHUB_ENV

        # Determine checkout ref (PR or branch)
        PR_NUMBER="${{ github.event.issue.number }}"
        if [ -z "$PR_NUMBER" ]; then PR_NUMBER="${{ github.event.pull_request.number }}"; fi
        
        SOURCE_REPO=""
        CHECKOUT_REF=""

        if [ -n "$PR_NUMBER" ] && [ "$PR_NUMBER" != "null" ]; then
           API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER"
           PR_DATA=$(curl -sS -H "Authorization: token ${{ inputs.github_token }}" "$API_URL" || echo "{}")
           SOURCE_REPO=$(echo "$PR_DATA" | jq -r '.head.repo.full_name // empty')
           CHECKOUT_REF=$(echo "$PR_DATA" | jq -r '.head.ref // empty')
        fi

        if [ -n "$SOURCE_REPO" ]; then
           echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_ENV
           echo "CHECKOUT_REF=$CHECKOUT_REF" >> $GITHUB_ENV
        else
           echo "SOURCE_REPO=${{ github.repository }}" >> $GITHUB_ENV
           echo "CHECKOUT_REF=$SYNC_BRANCH" >> $GITHUB_ENV
        fi

    - name: Notify Start
      if: ${{ env.SKIP == 'false' }}
      uses: ./actions/notify
      with:
        github_token: ${{ env.COMMENT_TOKEN }}
        pr_number: ${{ github.event.issue.number || github.event.pull_request.number }}
        pr_message: "🚀 Sincronizando configuración desde rama `${{ env.SYNC_BRANCH }}` hacia `${{ env.TARGET_ENV }}`..."

    - name: Checkout Source Repo
      if: ${{ env.SKIP == 'false' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ env.SOURCE_REPO }}
        ref: ${{ env.CHECKOUT_REF }}
        path: source-repo

    - name: Normalize GitOps Repo
      if: ${{ env.SKIP == 'false' }}
      shell: bash
      run: |
        RAW="${{ inputs.gitops_repo }}"
        repo="${RAW#https://github.com/}"
        repo="${repo%.git}"
        echo "GITOPS_REPO=$repo" >> $GITHUB_ENV

    - name: Checkout GitOps Repo
      if: ${{ env.SKIP == 'false' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ env.GITOPS_REPO }}
        token: ${{ inputs.github_token }}
        path: gitops-repo
        ref: ${{ inputs.branch }}

    - name: Ensure yq
      if: ${{ env.SKIP == 'false' }}
      shell: bash
      run: |
        if ! command -v yq >/dev/null 2>&1; then
          curl -sSL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
        fi

    - name: Update ConfigMap
      if: ${{ env.SKIP == 'false' }}
      shell: bash
      working-directory: gitops-repo
      env:
        SOURCE_FILE: ${{ github.workspace }}/source-repo/${{ env.SOURCE_FILE_PATH }}
        TARGET_FILE: ${{ env.TARGET_CONFIGMAP }}
        KEY: ${{ inputs.configmap_key }}
      run: |
        set -e
        if [ ! -f "$SOURCE_FILE" ] || [ ! -f "$TARGET_FILE" ]; then
           echo "❌ Error: Archivo origen o destino no encontrado."
           exit 1
        fi
        sed -i 's/[[:space:]]*$//' "$SOURCE_FILE"
        yq eval -i ".data[\"$KEY\"] = load_str(\"$SOURCE_FILE\") | .data[\"$KEY\"] style=\"literal\"" "$TARGET_FILE"

    - name: Create PR
      if: ${{ env.SKIP == 'false' }}
      id: create-pr
      uses: ./actions/create-pr
      with:
        token: ${{ inputs.github_token }}
        repo: ${{ env.GITOPS_REPO }}
        base_branch: ${{ inputs.branch }}
        head_branch: "config-sync/${{ env.TARGET_ENV }}-${{ github.run_id }}"
        commit_message: "${{ inputs.commit_message }} (${{ env.TARGET_ENV }})"
        pr_title: "${{ inputs.commit_message }} (${{ env.TARGET_ENV }})"
        pr_body: "Automatic update of config from workflow run ${{ github.run_id }}"
        working_directory: "gitops-repo"

    - name: Report Result
      if: always() && env.SKIP == 'false'
      uses: ./actions/notify
      with:
        github_token: ${{ env.COMMENT_TOKEN }}
        pr_number: ${{ github.event.issue.number || github.event.pull_request.number }}
        pr_message: |
          ${{ steps.create-pr.outputs.pr_url != '' && ':white_check_mark: Configuración sincronizada exitosamente.\nPR en GitOps: ' || '' }}${{ steps.create-pr.outputs.pr_url }}
          ${{ steps.create-pr.outputs.pr_url == '' && ':x: Falló la creación de la PR.' || '' }}
