name: Sync Config to GitOps
description: >
  Syncs a local file (e.g., application.yml) to a ConfigMap in a GitOps repository.
  Triggered by a PR comment: `sync -b <branch> -e <env>`.

inputs:
  staging_source_file:
    description: 'Path to the local source file for Staging.'
    required: true
  prod_source_file:
    description: 'Path to the local source file for Production.'
    required: true
  staging_configmap:
    description: 'Path to the Staging ConfigMap YAML file in the GitOps repository.'
    required: true
  prod_configmap:
    description: 'Path to the Prod ConfigMap YAML file in the GitOps repository.'
    required: true
  gitops_repo:
    description: 'GitOps repository in format owner/repo.'
    required: true
  github_token:
    description: 'Token with write permissions to the GitOps repo.'
    required: true
  source_repo_token:
    description: 'Token to comment in the source PR.'
    required: false
    default: ''
  branch:
    description: 'Base branch in the GitOps repo (default: main).'
    required: false
    default: 'main'
  configmap_key:
    description: 'Key in the ConfigMap data to update.'
    required: false
    default: 'application.yml'
  commit_message:
    description: 'Commit message.'
    required: false
    default: 'chore: update application.yml config'

runs:
  using: composite
  steps:
    - name: Initialize
      shell: bash
      run: |
        if [ -n "${{ inputs.source_repo_token }}" ]; then
          echo "COMMENT_TOKEN=${{ inputs.source_repo_token }}" >> $GITHUB_ENV
        else
          echo "COMMENT_TOKEN=${{ inputs.github_token }}" >> $GITHUB_ENV
        fi

    - name: Parse Sync Command
      id: parse
      uses: ./internal/parse-comment
      with:
        comment_body: ${{ github.event.comment.body }}
        command_prefix: "sync"

    - name: Determine Context
      id: ctx
      uses: ./internal/sync-context-determine
      with:
        staging_source: ${{ inputs.staging_source_file }}
        prod_source: ${{ inputs.prod_source_file }}
        staging_configmap: ${{ inputs.staging_configmap }}
        prod_configmap: ${{ inputs.prod_configmap }}
        parsed_branch: ${{ steps.parse.outputs.branch }}
        parsed_env: ${{ steps.parse.outputs.env }}
        is_valid_command: ${{ steps.parse.outputs.is_valid }}
        github_token: ${{ inputs.github_token }}

    - name: Notify Start
      if: ${{ steps.ctx.outputs.skip == 'false' }}
      uses: ./internal/notify
      with:
        github_token: ${{ env.COMMENT_TOKEN }}
        pr_number: ${{ github.event.issue.number || github.event.pull_request.number }}
        pr_message: "🚀 Sincronizando configuración desde rama `${{ steps.ctx.outputs.sync_branch }}` hacia `${{ steps.ctx.outputs.target_env }}`..."

    - name: Checkout Source Repo
      if: ${{ steps.ctx.outputs.skip == 'false' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ steps.ctx.outputs.source_repo }}
        ref: ${{ steps.ctx.outputs.checkout_ref }}
        path: source-repo

    - name: Normalize GitOps Repo
      if: ${{ steps.ctx.outputs.skip == 'false' }}
      id: norm
      uses: ./internal/util-normalize-repo
      with:
        repo_input: ${{ inputs.gitops_repo }}

    - name: Checkout GitOps Repo
      if: ${{ steps.ctx.outputs.skip == 'false' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ steps.norm.outputs.repo_normalized }}
        token: ${{ inputs.github_token }}
        path: gitops-repo
        ref: ${{ inputs.branch }}

    - name: Ensure yq
      if: ${{ steps.ctx.outputs.skip == 'false' }}
      shell: bash
      run: |
        if ! command -v yq >/dev/null 2>&1; then
          curl -sSL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
        fi

    - name: Update ConfigMap
      if: ${{ steps.ctx.outputs.skip == 'false' }}
      shell: bash
      working-directory: gitops-repo
      env:
        SOURCE_FILE: ${{ github.workspace }}/source-repo/${{ steps.ctx.outputs.source_file_path }}
        TARGET_FILE: ${{ steps.ctx.outputs.target_configmap }}
        KEY: ${{ inputs.configmap_key }}
      run: |
        set -e
        if [ ! -f "$SOURCE_FILE" ] || [ ! -f "$TARGET_FILE" ]; then
           echo "❌ Error: Archivo origen o destino no encontrado."
           exit 1
        fi
        sed -i 's/[[:space:]]*$//' "$SOURCE_FILE"
        yq eval -i ".data[\"$KEY\"] = load_str(\"$SOURCE_FILE\") | .data[\"$KEY\"] style=\"literal\"" "$TARGET_FILE"

    - name: Create PR
      if: ${{ steps.ctx.outputs.skip == 'false' }}
      id: create-pr
      uses: ./internal/create-pr
      with:
        token: ${{ inputs.github_token }}
        repo: ${{ steps.norm.outputs.repo_normalized }}
        base_branch: ${{ inputs.branch }}
        head_branch: "config-sync/${{ steps.ctx.outputs.target_env }}-${{ github.run_id }}"
        commit_message: "${{ inputs.commit_message }} (${{ steps.ctx.outputs.target_env }})"
        pr_title: "${{ inputs.commit_message }} (${{ steps.ctx.outputs.target_env }})"
        pr_body: "Automatic update of config from workflow run ${{ github.run_id }}"
        working_directory: "gitops-repo"

    - name: Report Result
      if: always() && steps.ctx.outputs.skip == 'false'
      uses: ./internal/notify
      with:
        github_token: ${{ env.COMMENT_TOKEN }}
        pr_number: ${{ github.event.issue.number || github.event.pull_request.number }}
        pr_message: |
          ${{ steps.create-pr.outputs.pr_url != '' && ':white_check_mark: Configuración sincronizada exitosamente.\nPR en GitOps: ' || '' }}${{ steps.create-pr.outputs.pr_url }}
          ${{ steps.create-pr.outputs.pr_url == '' && ':x: Falló la creación de la PR.' || '' }}
