name: Sync Config to GitOps
description: >
  Syncs a local file (e.g., application.yml) to a ConfigMap in a GitOps repository.
  Triggered by PR or issue comment: `sync -b <branch> -e <env>`.

inputs:
  staging_source_file:
    description: 'Path to the local source file for Staging.'
    required: true
  prod_source_file:
    description: 'Path to the local source file for Production.'
    required: true
  staging_configmap:
    description: 'Path to the Staging ConfigMap YAML file in the GitOps repository.'
    required: true
  prod_configmap:
    description: 'Path to the Prod ConfigMap YAML file in the GitOps repository.'
    required: true
  gitops_repo:
    description: 'GitOps repository in format owner/repo.'
    required: true
  github_token:
    description: 'Token with write permissions to the GitOps repo.'
    required: true
  source_repo_token:
    description: 'Token to comment in the source PR.'
    required: false
    default: ''
  branch:
    description: 'Base branch in the GitOps repo (default: main).'
    required: false
    default: 'main'
  configmap_key:
    description: 'Key in the ConfigMap data to update.'
    required: false
    default: 'application.yml'
  commit_message:
    description: 'Commit message.'
    required: false
    default: 'chore: update application.yml config'

runs:
  using: composite
  steps:
    - name: Initialize
      uses: Automya/CI-CD-template/internal/sync-context-init@main
      with:
        source_repo_token: ${{ inputs.source_repo_token }}
        github_token: ${{ inputs.github_token }}

    - name: Parse Sync Command
      id: parse
      uses: Automya/CI-CD-template/internal/parse-comment@main
      with:
        comment_body: ${{ github.event.comment.body }}
        command_prefix: "sync"

    - name: Determine Context
      id: ctx
      uses: Automya/CI-CD-template/internal/sync-context-determine@main
      with:
        staging_source: ${{ inputs.staging_source_file }}
        prod_source: ${{ inputs.prod_source_file }}
        staging_configmap: ${{ inputs.staging_configmap }}
        prod_configmap: ${{ inputs.prod_configmap }}
        parsed_branch: ${{ steps.parse.outputs.branch }}
        parsed_env: ${{ steps.parse.outputs.env }}
        is_valid_command: ${{ steps.parse.outputs.is_valid }}
        github_token: ${{ inputs.github_token }}

    - name: Notify Start
      if: ${{ steps.ctx.outputs.skip == 'false' }}
      uses: Automya/CI-CD-template/internal/notify@main
      with:
        github_token: ${{ env.COMMENT_TOKEN }}
        pr_number: ${{ github.event.issue.number || github.event.pull_request.number }}
        pr_message: "游 Sincronizando configuraci칩n desde rama `${{ steps.ctx.outputs.sync_branch }}` hacia `${{ steps.ctx.outputs.target_env }}`..."

    - name: Checkout Source Repo
      if: ${{ steps.ctx.outputs.skip == 'false' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ steps.ctx.outputs.source_repo }}
        ref: ${{ steps.ctx.outputs.checkout_ref }}
        path: source-repo

    - name: Normalize GitOps Repo
      if: ${{ steps.ctx.outputs.skip == 'false' }}
      id: norm
      uses: Automya/CI-CD-template/internal/util-normalize-repo@main
      with:
        repo_input: ${{ inputs.gitops_repo }}

    - name: Checkout GitOps Repo
      if: ${{ steps.ctx.outputs.skip == 'false' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ steps.norm.outputs.repo_normalized }}
        token: ${{ inputs.github_token }}
        path: gitops-repo
        ref: ${{ inputs.branch }}

    - name: Update ConfigMap
      if: ${{ steps.ctx.outputs.skip == 'false' }}
      uses: Automya/CI-CD-template/internal/sync-update-configmap@main
      with:
        source_file: ${{ github.workspace }}/source-repo/${{ steps.ctx.outputs.source_file_path }}
        target_file: ${{ steps.ctx.outputs.target_configmap }}
        configmap_key: ${{ inputs.configmap_key }}
        working_directory: gitops-repo

    - name: Create GitOps PR
      if: ${{ steps.ctx.outputs.skip == 'false' }}
      id: gitops-pr
      uses: Automya/CI-CD-template/internal/create-pr@main
      with:
        token: ${{ inputs.github_token }}
        repo: ${{ steps.norm.outputs.repo_normalized }}
        base_branch: ${{ inputs.branch }}
        head_branch: "sync/${{ steps.ctx.outputs.target_env }}/${{ steps.ctx.outputs.sync_branch }}"
        commit_message: ${{ inputs.commit_message }}
        pr_title: "chore(${{ steps.ctx.outputs.target_env }}): sync config from ${{ steps.ctx.outputs.sync_branch }}"
        pr_body: "Sincronizaci칩n autom치tica de configuraci칩n desde rama `${{ steps.ctx.outputs.sync_branch }}` hacia `${{ steps.ctx.outputs.target_env }}`."
        files_to_commit: ${{ steps.ctx.outputs.target_configmap }}
        working_directory: gitops-repo

    - name: Set Environment Variables
      if: ${{ steps.ctx.outputs.skip == 'false' }}
      uses: Automya/CI-CD-template/internal/sync-set-env@main
      with:
        gitops_pr_url: ${{ steps.gitops-pr.outputs.pr_url }}
        sync_branch: ${{ steps.ctx.outputs.sync_branch }}
        target_env: ${{ steps.ctx.outputs.target_env }}

    - name: Report Result
      if: always() && env.SKIP != 'true'
      uses: Automya/CI-CD-template/internal/sync-report@main
      with:
        github_token: ${{ inputs.github_token }}
        gitops_pr_url: ${{ env.GITOPS_PR_URL }}
        sync_branch: ${{ env.SYNC_BRANCH }}
        target_env: ${{ env.TARGET_ENV }}
        error_file_path: ${{ github.workspace }}/action_error.txt
