name: "GCP Docker Build & Push with PR feedback"
description: "Builds and pushes Docker images to GCP Artifact Registry using Workload Identity Federation and reports back to PR comments in PRs."
inputs:
  gitops_repo:
    description: "Repo GitOps destino en formato owner/repo (ej: Automya/gitops)."
    required: false
  prod_manifest_path:
    description: "Ruta del manifiesto Kubernetes para producción dentro del repo GitOps."
    required: false
  gitops_token:
    description: "Token con permisos write en el repo GitOps."
    required: false
  container_name:
    description: "Nombre del contenedor a actualizar en el manifiesto (opcional, usa IMAGE_NAME si no se define)."
    required: false
  google_chat_webhook:
    description: "Webhook URL para notificaciones a Google Chat (opcional)."
    required: false

runs:
  using: "composite"
  steps:
    - name: Notify Start
      if: github.event_name == 'issue_comment'
      uses: ./actions/notify
      with:
        github_token: ${{ env.GH_TOKEN }}
        pr_number: ${{ github.event.issue.number }}
        webhook_url: ${{ inputs.google_chat_webhook }}
        pr_message: "🚀 Iniciando Build, espere por favor..."
        chat_message: |
          🚀 **Iniciando Build**
          - **Repo:** ${{ github.repository }}
          - **PR:** #${{ github.event.issue.number }}
          - [Ver Logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          ⏳ Iniciando...

    - name: Parse Comment (if applicable)
      if: github.event_name == 'issue_comment'
      id: parse
      uses: ./actions/parse-comment
      with:
        comment_body: ${{ github.event.comment.body }}
        command_prefix: "build"

    - name: Determine Context
      id: context
      shell: bash
      env:
        EVENT: ${{ github.event_name }}
        PR_BRANCH: ${{ steps.parse.outputs.branch }}
        PR_TAG: ${{ steps.parse.outputs.tag }}
        IS_VALID: ${{ steps.parse.outputs.is_valid }}
        GH_TOKEN: ${{ env.GH_TOKEN }}
      run: |
        TAG=""
        BRANCH=""
        SAFE_BRANCH=""
        LOGICAL_STATUS=""
        JOB_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

        if [[ "$EVENT" == "issue_comment" ]]; then
           if [[ "$IS_VALID" != "true" ]]; then
              echo "status=not_build_command" >> "$GITHUB_OUTPUT"
              exit 0
           fi

           BRANCH="$PR_BRANCH"
           if [[ -z "$BRANCH" ]]; then
             # Fetch branch from PR API
             PR_URL=$(jq -r '.issue.pull_request.url // empty' < "$GITHUB_EVENT_PATH")
             BRANCH=$(curl -s -H "Authorization: token $GH_TOKEN" "$PR_URL" | jq -r .head.ref)
           fi
           
           SAFE_BRANCH=$(echo "$BRANCH" | tr '/' '-')
           TAG="${PR_TAG:-$SAFE_BRANCH}"
           
           # Validation logic
           is_semver() { [[ "$1" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; }

           if [[ "$BRANCH" == "main" && -n "$PR_TAG" && "$PR_TAG" != "main" ]]; then
             if ! is_semver "$PR_TAG"; then LOGICAL_STATUS="invalid_tag_main"; fi
           elif [[ "$BRANCH" != "main" && -n "$PR_TAG" ]]; then
             if is_semver "$PR_TAG"; then LOGICAL_STATUS="invalid_tag_branch"; fi
           fi

        elif [[ "$EVENT" == "release" ]]; then
           TAG="${{ github.event.release.tag_name }}"
           BRANCH="${{ github.event.release.target_commitish }}"
           if [[ "$BRANCH" != "main" ]]; then LOGICAL_STATUS="invalid_release_branch"; fi
        else
           LOGICAL_STATUS="not_supported_event"
        fi

        echo "branch=$BRANCH" >> "$GITHUB_OUTPUT"
        echo "safe_branch=$SAFE_BRANCH" >> "$GITHUB_OUTPUT"
        echo "tag=$TAG" >> "$GITHUB_OUTPUT"
        echo "job_url=$JOB_URL" >> "$GITHUB_OUTPUT"
        echo "status=$LOGICAL_STATUS" >> "$GITHUB_OUTPUT"

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.context.outputs.branch }}

    - name: Setup GCP & Docker
      uses: ./actions/setup-gcp
      with:
        region: ${{ env.GCP_REGION }}

    - name: Build and push image
      if: steps.context.outputs.status == ''
      id: build
      shell: bash
      env: 
        TAG: ${{ steps.context.outputs.tag }}
      run: |
        FULL_IMAGE="$GCP_REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$TAG"
        
        docker build \
          --build-arg MAVEN_USERNAME="${MAVEN_USERNAME}" \
          --build-arg MAVEN_PASSWORD="${MAVEN_PASSWORD}" \
          --build-arg MAVEN_USERNAME2="${MAVEN_USERNAME2}" \
          --build-arg MAVEN_PASSWORD2="${MAVEN_PASSWORD2}" \
          -t "$FULL_IMAGE" . || { echo "status=build_failed" >> "$GITHUB_OUTPUT"; exit 0; }
        
        docker push "$FULL_IMAGE" || { echo "status=push_failed" >> "$GITHUB_OUTPUT"; exit 0; }
        
        echo "status=success" >> "$GITHUB_OUTPUT"

    - name: GitOps Update (Release only)
      if: github.event_name == 'release' && steps.build.outputs.status == 'success'
      uses: ./actions/gitops-pr
      with:
        gitops_repo: ${{ inputs.gitops_repo }}
        gitops_token: ${{ inputs.gitops_token }}
        manifest_path: ${{ inputs.prod_manifest_path }}
        container_name: ${{ inputs.container_name || env.IMAGE_NAME }}
        image_tag: ${{ steps.context.outputs.tag }}
        target_env: "prod"

    - name: Prepare Notification Message
      if: github.event_name == 'issue_comment'
      id: msg
      shell: bash
      env:
        # Combine status from context (validation errors) or build (execution errors)
        STATUS: ${{ steps.context.outputs.status || steps.build.outputs.status }}
        JOB_URL: ${{ steps.context.outputs.job_url }}
        IMAGE: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ steps.context.outputs.tag }}
      run: |
        PR_MSG=""
        CHAT_MSG=""
        
        case "$STATUS" in
          "not_build_command") PR_MSG="❌ Error: Comando inválido.";;
          "invalid_tag_main") PR_MSG="❌ Error: Solo tags semánticos en main.";;
          "invalid_tag_branch") PR_MSG="❌ Error: Tags semánticos solo en main.";;
          "build_failed") 
             PR_MSG="❌ Build fallido."
             CHAT_MSG="❌ **Build Fallido**\n- [Logs]($JOB_URL)"
             ;;
          "push_failed")
             PR_MSG="❌ Push fallido."
             CHAT_MSG="❌ **Push Fallido**\n- [Logs]($JOB_URL)"
             ;;
          "success")
             PR_MSG="🎉 Éxito: Imagen subida."
             CHAT_MSG="✅ **Exito**\n- **Img:** \`$IMAGE\`"
             ;;
        esac

        echo "pr_msg<<EOF" >> "$GITHUB_OUTPUT"
        echo "$PR_MSG" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

        echo "chat_msg<<EOF" >> "$GITHUB_OUTPUT"
        echo "$CHAT_MSG" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

    - name: Notify Result
      if: github.event_name == 'issue_comment'
      uses: ./actions/notify
      with:
        github_token: ${{ env.GH_TOKEN }}
        pr_number: ${{ github.event.issue.number }}
        webhook_url: ${{ inputs.google_chat_webhook }}
        pr_message: ${{ steps.msg.outputs.pr_msg }}
        chat_message: ${{ steps.msg.outputs.chat_msg }}
