name: "GCP Docker Build & Push (Frontend)"
description: |
  Builds and pushes Docker images to GCP Artifact Registry with Maven credentials and GitOps.
  Optimized for frontend builds. Allows DEV tags and semantic versioning on main and DEV branches. Supports PR comments and issue comments (use 'build -b <branch>' for issues).

  REQUIRED WORKFLOW PERMISSIONS for issue_comment trigger:
    permissions:
      contents: read
      issues: write
      pull-requests: write
      id-token: write
inputs:
  workload_identity_provider:
    description: "GCP Workload Identity Provider resource name"
    required: true
  service_account:
    description: "GCP Service Account email"
    required: true
  gitops_repo:
    description: "GitOps repository in format owner/repo"
    required: false
  prod_manifest_path:
    description: "Path to the production manifest in GitOps repo"
    required: false
  gitops_token:
    description: "Token with write permissions to GitOps repo"
    required: false
  container_name:
    description: "Container name to update in manifest"
    required: false
  google_chat_webhook:
    description: "Google Chat Webhook URL for notifications"
    required: false
  cache_enabled:
    description: "Enable Docker layer caching (uses GCP Artifact Registry)"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Build and Push
      uses: Automya/CI-CD-template/actions/build-image-docker@main
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}
        gitops_repo: ${{ inputs.gitops_repo }}
        prod_manifest_path: ${{ inputs.prod_manifest_path }}
        gitops_token: ${{ inputs.gitops_token }}
        container_name: ${{ inputs.container_name }}
        google_chat_webhook: ${{ inputs.google_chat_webhook }}
        cache_enabled: ${{ inputs.cache_enabled }}
        allowed_tags: "DEV,dev,SEMVER"
        build_args: |
          MAVEN_USERNAME=${{ env.MAVEN_USERNAME }}
          MAVEN_PASSWORD=${{ env.MAVEN_PASSWORD }}
          MAVEN_USERNAME2=${{ env.MAVEN_USERNAME2 }}
          MAVEN_PASSWORD2=${{ env.MAVEN_PASSWORD2 }}
