name: "GCP Docker Build & Push with PR feedback"
description: "Builds and pushes Docker images to GCP Artifact Registry using Workload Identity Federation and reports back to PR comments in PRs."
inputs:
  gitops_repo:
    description: "Repo GitOps destino en formato owner/repo (ej: Automya/gitops)."
    required: false
  prod_manifest_path:
    description: "Ruta del manifiesto Kubernetes para producción dentro del repo GitOps."
    required: false
  gitops_token:
    description: "Token con permisos write en el repo GitOps."
    required: false
  container_name:
    description: "Nombre del contenedor a actualizar en el manifiesto (opcional, usa IMAGE_NAME si no se define)."
    required: false
  google_chat_webhook:
    description: "Webhook URL para notificaciones a Google Chat (opcional)."
    required: false

runs:
  using: "composite"
  steps:
    - name: Notify Start
      if: github.event_name == 'issue_comment'
      uses: ./actions/notify
      with:
        github_token: ${{ env.GH_TOKEN }}
        pr_number: ${{ github.event.issue.number }}
        webhook_url: ${{ inputs.google_chat_webhook }}
        pr_message: "🚀 Iniciando Build, espere por favor..."
        chat_message: |
          🚀 **Iniciando Build**
          - **Repo:** ${{ github.repository }}
          - **PR:** #${{ github.event.issue.number }}
          - [Ver Logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          ⏳ Iniciando...

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup GCP & Docker
      uses: ./actions/setup-gcp
      with:
        region: ${{ env.GCP_REGION }}

    - name: Determine build context
      id: context
      shell: bash
      run: |
        EVENT="${{ github.event_name }}"
        TAG=""
        BRANCH=""
        SAFE_BRANCH=""
        LOGICAL_STATUS=""
        COMMENT_BODY="${{ github.event.comment.body }}"
        CLEAN_BODY="$(echo "$COMMENT_BODY" | sed -E 's/^[[:space:]]+//')"
        PR_NUMBER=$(jq -r '.issue.number // empty' < "$GITHUB_EVENT_PATH")
        JOB_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

        comment_pr() {
          MSG="$1"
          if [[ -n "$PR_NUMBER" ]]; then
            curl -s -H "Authorization: token $GH_TOKEN" \
              -X POST \
              -d "{\"body\":\"$MSG\"}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments" > /dev/null
          fi
        }

        if [[ "$EVENT" == "issue_comment" && "$(jq -r '.issue.pull_request // empty' < "$GITHUB_EVENT_PATH")" != "" ]]; then
          if [[ "$CLEAN_BODY" =~ ^[Bb]uild($|[[:space:]]) ]]; then
            [[ "$CLEAN_BODY" =~ -t[[:space:]]+([^\ ]+) ]] && TAG="${BASH_REMATCH[1]}" || TAG=""
            [[ "$CLEAN_BODY" =~ -b[[:space:]]+([^\ ]+) ]] && BRANCH="${BASH_REMATCH[1]}" || BRANCH=""
          else
            LOGICAL_STATUS="not_build_command"
          fi

          if [[ -z "$BRANCH" ]]; then
            PR_URL=$(jq -r '.issue.pull_request.url // empty' < "$GITHUB_EVENT_PATH")
            BRANCH=$(curl -s -H "Authorization: token $GH_TOKEN" "$PR_URL" | jq -r .head.ref)
          fi

          SAFE_BRANCH=$(echo "$BRANCH" | tr '/' '-')

          is_semver() { [[ "$1" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; }

          if [[ -z "$TAG" && -n "$BRANCH" ]]; then
            TAG="$SAFE_BRANCH"
          fi

          if [[ "$BRANCH" == "main" && -n "$TAG" && "$TAG" != "main" ]]; then
            if ! is_semver "$TAG"; then
              LOGICAL_STATUS="invalid_tag_main"
            fi
          elif [[ "$BRANCH" != "main" && -n "$TAG" ]]; then
            if is_semver "$TAG"; then
              LOGICAL_STATUS="invalid_tag_branch"
            fi
          fi

        elif [[ "$EVENT" == "release" && "${GITHUB_REF}" =~ ^refs/tags/v ]]; then
          TAG="${{ github.event.release.tag_name }}"
          BRANCH="${{ github.event.release.target_commitish }}"
          if [[ "$BRANCH" != "main" ]]; then
            LOGICAL_STATUS="invalid_release_branch"
            comment_pr "❌ Error: Release con tag ${TAG} no apunta a main. [Ver logs]($JOB_URL)"
          fi
        else
          LOGICAL_STATUS="not_supported_event"
        fi

        echo "branch=$BRANCH" >> "$GITHUB_OUTPUT"
        echo "safe_branch=$SAFE_BRANCH" >> "$GITHUB_OUTPUT"
        echo "tag=$TAG" >> "$GITHUB_OUTPUT"
        echo "job_url=$JOB_URL" >> "$GITHUB_OUTPUT"
        echo "status=$LOGICAL_STATUS" >> "$GITHUB_OUTPUT"

    - name: Checkout branch
      if: steps.context.outputs.branch != ''
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.context.outputs.branch }}

    - name: Build and push image
      if: steps.context.outputs.tag != ''
      id: build
      shell: bash
      run: |
        STATUS="${{ steps.context.outputs.status }}"
        if [[ "$STATUS" != "" && "$STATUS" != "success" ]]; then
          echo "status=$STATUS" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        TAG="${{ steps.context.outputs.tag }}"
        FULL_IMAGE="$GCP_REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$TAG"

        set +e
        docker build \
          --build-arg MAVEN_USERNAME="${MAVEN_USERNAME}" \
          --build-arg MAVEN_PASSWORD="${MAVEN_PASSWORD}" \
          --build-arg MAVEN_USERNAME2="${MAVEN_USERNAME2}" \
          --build-arg MAVEN_PASSWORD2="${MAVEN_PASSWORD2}" \
          -t "$FULL_IMAGE" .
        BUILD_STATUS=$?

        if [ $BUILD_STATUS -ne 0 ]; then
          echo "status=build_failed" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        docker push "$FULL_IMAGE"
        PUSH_STATUS=$?

        if [ $PUSH_STATUS -ne 0 ]; then
          echo "status=push_failed" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "status=success" >> "$GITHUB_OUTPUT"

    - name: Ensure yq is available
      if: github.event_name == 'release' && steps.build.outputs.status == 'success'
      shell: bash
      run: |
        if ! command -v yq >/dev/null 2>&1; then
          curl -sSL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
        fi

    - name: Checkout GitOps repository
      if: github.event_name == 'release' && steps.build.outputs.status == 'success'
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.gitops_repo }}
        token: ${{ inputs.gitops_token }}
        path: gitops-repo

    - name: Update manifest and Deploy to Prod
      if: github.event_name == 'release' && steps.build.outputs.status == 'success'
      shell: bash
      working-directory: gitops-repo
      env:
        TAG: ${{ steps.context.outputs.tag }}
        FILE: ${{ inputs.prod_manifest_path }}
        CONTAINER_NAME: ${{ inputs.container_name || env.IMAGE_NAME }}
        TOKEN: ${{ inputs.gitops_token }}
        GITOPS_REPO: ${{ inputs.gitops_repo }}
      run: |
        set -euo pipefail

        if [ -z "$FILE" ] || [ -z "$GITOPS_REPO" ] || [ -z "$TOKEN" ]; then
          echo "❌ Error: Faltan inputs requeridos para el despliegue."
          exit 1
        fi

        echo "Actualizando manifiesto $FILE con tag $TAG..."

        if [ ! -f "$FILE" ]; then
          echo "❌ Error: No existe el manifiesto $FILE"
          exit 1
        fi

        yq eval -i "(.spec.template.spec.containers[] | select(.name == \"$CONTAINER_NAME\").image) |= sub(\":.*$\", \":$TAG\")" "$FILE"

        if git diff --quiet -- "$FILE"; then
          echo "⚠️ El manifiesto ya tiene el tag $TAG. No se requieren cambios."
          exit 0
        fi

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        BRANCH="deploy/prod/${CONTAINER_NAME}-${TAG}"
        git checkout -b "$BRANCH"
        git add "$FILE"
        git commit -m "chore(prod): update ${CONTAINER_NAME} image to ${TAG}"
        git push --force "https://x-access-token:${TOKEN}@github.com/${GITOPS_REPO}.git" "$BRANCH"

        PR_TITLE="chore(prod): update ${CONTAINER_NAME} to ${TAG}"
        PR_BODY="Release automático ${TAG}."

        api_url="https://api.github.com/repos/${GITOPS_REPO}/pulls"
        payload=$(printf '{"title":"%s","head":"%s","base":"main","body":"%s"}' "$PR_TITLE" "$BRANCH" "$PR_BODY")

        pr_response=$(curl -sS -X POST -H "Authorization: token ${TOKEN}" \
          -H "Accept: application/vnd.github+json" "$api_url" -d "$payload")
        pr_number=$(echo "$pr_response" | jq -r .number)

        if [ "$pr_number" == "null" ]; then
          echo "❌ Error creando PR: $pr_response"
          exit 1
        fi

        echo "✅ PR creada: #$pr_number"

        merge_url="https://api.github.com/repos/${GITOPS_REPO}/pulls/${pr_number}/merge"
        merge_payload='{"merge_method":"merge"}'
        curl -sS -X PUT -H "Authorization: token ${TOKEN}" \
          -H "Accept: application/vnd.github+json" "$merge_url" -d "$merge_payload"
          
        echo "🚀 Despliegue a producción iniciado (PR mergeada)."

    - name: Prepare Notification Message
      if: github.event_name == 'issue_comment'
      id: msg
      shell: bash
      env:
        STATUS: ${{ steps.build.outputs.status }}
        JOB_URL: ${{ steps.context.outputs.job_url }}
        TAG: ${{ steps.context.outputs.tag }}
        IMAGE: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ steps.context.outputs.tag }}
      run: |
        PR_MSG=""
        CHAT_MSG=""
        
        case "$STATUS" in
          "not_build_command")
            PR_MSG="❌ Error: El comando del comentario debe empezar con 'build'."
            ;;
          "invalid_tag_main")
            PR_MSG="❌ Error: Solo se permiten tags semánticos en main."
            ;;
          "invalid_tag_branch")
            PR_MSG="❌ Error: Tags semánticos solo están permitidos en main."
            ;;
          "invalid_release_branch")
            PR_MSG="❌ Error: Release con tag no apunta a main."
            ;;
          "not_supported_event")
            PR_MSG="❌ Error: Tipo de evento no soportado."
            ;;
          "build_failed")
            PR_MSG="❌ Error: Falló la construcción de la imagen ${IMAGE}."
            CHAT_MSG="❌ **Build Fallido**\n- **Imagen:** \`$IMAGE\`\n- [Ver Logs]($JOB_URL)"
            ;;
          "push_failed")
            PR_MSG="❌ Error: Falló el push de la imagen ${IMAGE}."
            CHAT_MSG="❌ **Push Fallido**\n- **Imagen:** \`$IMAGE\`\n- [Ver Logs]($JOB_URL)"
            ;;
          "success")
            PR_MSG="🎉 Éxito: Imagen ${IMAGE} subida correctamente."
            CHAT_MSG="✅ **Build Exitoso**\n- **Imagen:** \`$IMAGE\`\n- [Ver Logs]($JOB_URL)"
            ;;
        esac

        echo "pr_msg<<EOF" >> "$GITHUB_OUTPUT"
        echo "$PR_MSG" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

        echo "chat_msg<<EOF" >> "$GITHUB_OUTPUT"
        echo "$CHAT_MSG" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

    - name: Notify Result
      if: github.event_name == 'issue_comment'
      uses: ./actions/notify
      with:
        github_token: ${{ env.GH_TOKEN }}
        pr_number: ${{ github.event.issue.number }}
        webhook_url: ${{ inputs.google_chat_webhook }}
        pr_message: ${{ steps.msg.outputs.pr_msg }}
        chat_message: ${{ steps.msg.outputs.chat_msg }}
