name: "Setup GCP & Docker"
description: "Authenticates to GCP using Workload Identity Federation and configures Docker."
inputs:
  workload_identity_provider:
    description: "GCP Workload Identity Provider resource name (required)"
    required: true
  service_account:
    description: "GCP Service Account email (required)"
    required: true
  region:
    description: "GCP Region for Artifact Registry (e.g. us-central1)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [ -z "${{ inputs.workload_identity_provider }}" ]; then
          echo "::error::workload_identity_provider is required"
          exit 1
        fi
        if [ -z "${{ inputs.service_account }}" ]; then
          echo "::error::service_account is required"
          exit 1
        fi
        if [ -z "${{ inputs.region }}" ]; then
          echo "::error::region is required"
          exit 1
        fi

    - name: Clean GCP credential env vars
      shell: bash
      run: |
        # Clear any existing credentials to avoid conflicts
        for var in GOOGLE_APPLICATION_CREDENTIALS CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE GOOGLE_GHA_CREDS_PATH GCP_SA_KEY; do
          unset "$var" 2>/dev/null || true
          export "$var="
        done

    - name: Install gcloud SDK
      uses: google-github-actions/setup-gcloud@v2
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ""
        CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: ""
        GOOGLE_GHA_CREDS_PATH: ""
        GCP_SA_KEY: ""

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        create_credentials_file: true
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Configure Docker for GCP
      shell: bash
      env:
        REGION: ${{ inputs.region }}
      run: |
        if ! gcloud auth configure-docker "${REGION}-docker.pkg.dev" --quiet; then
          echo "::error::Failed to configure Docker for GCP Artifact Registry"
          exit 1
        fi

