name: Deploy GitOps Image
description: >
  Actualiza el tag de una imagen en el repo de GitOps (staging o prod) leyendo el
  comando `deploy -t <tag> -e <env>` desde un comentario de PR y sube los cambios
  al repositorio GitOps mediante una PR automática.
inputs:
  gitops_repo:
    description: 'Repo GitOps destino en formato owner/repo o URL (ej: Automya/gitops).'
    required: true
  staging_manifest_path:
    description: 'Ruta del manifiesto Kubernetes para staging dentro del repo GitOps.'
    required: true
  prod_manifest_path:
    description: 'Ruta del manifiesto Kubernetes para producción dentro del repo GitOps.'
    required: true
  image_name:
    description: 'Nombre del contenedor (.spec.template.spec.containers[].name) a modificar.'
    required: true
  github_token:
    description: 'Token con permisos write en el repo GitOps (PAT o GITHUB_TOKEN elevado).'
    required: true
  source_repo_token:
    description: 'Token para comentar en la PR origen (opcional, default usa github_token).'
    required: false
    default: ''
  base_branch:
    description: 'Rama base en el repo GitOps (main por defecto).'
    required: false
    default: 'main'
  pr_title:
    description: 'Título base de la PR que se creará en el repo GitOps.'
    required: false
    default: 'chore: update image tag'
  staging_cluster_name:
    description: 'Staging GKE Cluster Name'
    required: true
  prod_cluster_name:
    description: 'Prod GKE Cluster Name'
    required: true
  staging_cluster_location:
    description: 'Staging GKE Cluster Location'
    required: true
  prod_cluster_location:
    description: 'Prod GKE Cluster Location'
    required: true
  project_id:
    description: 'GCP Project ID (shared for both clusters)'
    required: true
  deployment_name:
    description: 'K8s Deployment name to restart (defaults to image_name if not set)'
    required: false
  namespace:
    description: 'K8s Namespace (default: default)'
    required: false
    default: 'default'
runs:
  using: composite
  steps:
    - name: Initialize action context
      shell: bash
      run: |
        set -euo pipefail
        : > "$GITHUB_WORKSPACE/action_error.txt"
        if [ -n "${{ inputs.source_repo_token }}" ]; then
          echo "COMMENT_TOKEN=${{ inputs.source_repo_token }}" >> $GITHUB_ENV
        else
          echo "COMMENT_TOKEN=${{ inputs.github_token }}" >> $GITHUB_ENV
        fi
        echo "SKIP=false" >> $GITHUB_ENV

    - name: Parse deploy command from PR comment
      shell: bash
      run: |
        set -euo pipefail
        BODY="${{ github.event.comment.body || '' }}"
        
        echo "Comentario recibido:"
        echo "$BODY"
        
        if echo "$BODY" | grep -qE '^[:white_check_mark:]|^[:x:]|^Imagen actualizada|^No se pudo actualizar'; then
          echo "El comentario parece ser una respuesta automática de esta acción. Se ignora para evitar loops infinitos."
          echo "SKIP=true" >> $GITHUB_ENV
          exit 0
        fi

        if [ -z "$BODY" ]; then
          echo "No hay comentario disponible. Esta acción solo responde a issue_comment."
          echo "SKIP=true" >> $GITHUB_ENV
          exit 0
        fi

        BODY_TRIMMED=$(echo "$BODY" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        
        if ! echo "$BODY_TRIMMED" | grep -qiE '^deploy[[:space:]]+-t[[:space:]]+[^[:space:]]+[[:space:]]+-e[[:space:]]+(staging|stage|st|stag|stg|prod|production|prd)'; then
          echo "El comentario no tiene el formato exacto requerido."
          echo "Formato esperado: 'deploy -t <tag> -e <staging|prod>' (en ese orden exacto)"
          echo "SKIP=true" >> $GITHUB_ENV
          exit 0
        fi

        TAG=$(echo "$BODY" | grep -oE '\-t[[:space:]]+([^[:space:]]+)' | sed -E 's/\-t[[:space:]]+//' | head -n1 || echo "")
        ENV_RAW=$(echo "$BODY" | grep -oE '\-e[[:space:]]+([^[:space:]]+)' | sed -E 's/\-e[[:space:]]+//' | head -n1 || echo "")

        if [ -z "$TAG" ] || [ -z "$ENV_RAW" ]; then
          echo "No se pudo extraer el tag o el entorno del comentario."
          echo "SKIP=true" >> $GITHUB_ENV
          exit 0
        fi

        ENV_LOWER=$(echo "$ENV_RAW" | tr '[:upper:]' '[:lower:]')
        case "$ENV_LOWER" in
          staging|stage|st|stag|stg)
            TARGET_ENV="staging"
            ;;
          prod|production|prd)
            TARGET_ENV="prod"
            ;;
          *)
            echo "Error: Valor de entorno no soportado: $ENV_RAW (aceptados: staging/stage/st/stag/stg o prod/production/prd)"
            exit 1
            ;;
        esac

        echo "DEPLOY_TAG=$TAG" >> $GITHUB_ENV
        echo "TARGET_ENV=$TARGET_ENV" >> $GITHUB_ENV
        echo "SKIP=false" >> $GITHUB_ENV
        
        echo "Comando detectado:"
        echo "  Tag: $TAG"
        echo "  Entorno: $TARGET_ENV"

    - name: Normalize GitOps repository reference
      if: ${{ env.SKIP == 'false' }}
      shell: bash
      run: |
        set -euo pipefail
        RAW="${{ inputs.gitops_repo }}"
        if [ -z "$RAW" ]; then
          echo "gitops_repo no puede ser vacío"
          exit 1
        fi
        repo="$RAW"
        repo="${repo#https://github.com/}"
        repo="${repo#http://github.com/}"
        repo="${repo#github.com/}"
        repo="${repo#git@github.com:}"
        repo="${repo#git@www.github.com:}"
        repo="${repo#www.github.com/}"
        repo="${repo#/}"
        repo="${repo%.git}"
        if ! echo "$repo" | grep -q '/'; then
          echo "No se pudo normalizar el repo GitOps (esperado owner/repo): $RAW"
          exit 1
        fi
        echo "GITOPS_REPO=$repo" >> $GITHUB_ENV
        echo "Repositorio GitOps normalizado: $repo"

    - name: Checkout GitOps repository
      if: ${{ env.SKIP == 'false' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ env.GITOPS_REPO }}
        token: ${{ inputs.github_token }}
        path: gitops-repo

    - name: Ensure yq is available
      if: ${{ env.SKIP == 'false' }}
      shell: bash
      run: |
        set -euo pipefail
        if ! command -v yq >/dev/null 2>&1; then
          curl -sSL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
        fi
        yq --version

    - name: Select manifest path
      if: ${{ env.SKIP == 'false' }}
      shell: bash
      run: |
        set -euo pipefail
        if [ "${{ env.TARGET_ENV }}" = "prod" ]; then
          manifest="${{ inputs.prod_manifest_path }}"
        else
          manifest="${{ inputs.staging_manifest_path }}"
        fi
        echo "MANIFEST_PATH=${manifest}" >> $GITHUB_ENV
        echo "Se usará el manifiesto: ${manifest}"

    - name: Update manifest with new tag
      if: ${{ env.SKIP == 'false' }}
      shell: bash
      working-directory: gitops-repo
      env:
        TAG: ${{ env.DEPLOY_TAG }}
        CONTAINER_NAME: ${{ inputs.image_name }}
        FILE: ${{ env.MANIFEST_PATH }}
      run: |
        set -euo pipefail
        ERRFILE="$GITHUB_WORKSPACE/action_error.txt"
        trap 'rc=$?; echo "ERROR actualizando manifiesto (exit $rc)" >> "$ERRFILE"; exit $rc' ERR

        if [ ! -f "$FILE" ]; then
          echo "No existe el manifiesto $FILE" | tee -a "$ERRFILE"
          exit 1
        fi

        container_count=$(yq eval '.spec.template.spec.containers | length' "$FILE" 2>/dev/null || echo "0")
        if [ "$container_count" = "null" ] || [ "$container_count" = "0" ]; then
          echo "No se encontraron contenedores en $FILE" | tee -a "$ERRFILE"
          exit 1
        fi

        found=0
        i=0
        while [ "$i" -lt "$container_count" ]; do
          container_name=$(yq eval -r ".spec.template.spec.containers[$i].name" "$FILE" 2>/dev/null || echo "")
          if [ "$container_name" = "$CONTAINER_NAME" ]; then
            current_image=$(yq eval -r ".spec.template.spec.containers[$i].image" "$FILE" 2>/dev/null || echo "")
            if [ -z "$current_image" ] || [ "$current_image" = "null" ]; then
              echo "El contenedor '${CONTAINER_NAME}' no tiene imagen definida en $FILE" | tee -a "$ERRFILE"
              exit 1
            fi

            base="$current_image"
            if [[ "$base" == *@* ]]; then
              base="${base%%@*}"
            elif [[ "$base" == *:* ]]; then
              base="${base%:*}"
            fi
            if [ -z "$base" ]; then
              base="$current_image"
            fi

            NEW_IMAGE="${base}:${TAG}"
            yq eval -i ".spec.template.spec.containers[$i].image = \"${NEW_IMAGE}\"" "$FILE"
            echo "Actualizado contenedor '${CONTAINER_NAME}': ${current_image} -> ${NEW_IMAGE}"
            found=1
            break
          fi
          i=$((i + 1))
        done

        if [ "$found" -eq 0 ]; then
          echo "No se encontró el contenedor '${CONTAINER_NAME}' en $FILE" | tee -a "$ERRFILE"
          exit 1
        fi

        if git diff --quiet -- "$FILE"; then
          echo "El manifiesto ya estaba en ${NEW_IMAGE}. Se requiere reinicio."
          echo "NEEDS_RESTART=true" >> $GITHUB_ENV
          echo "GITOPS_PR_URL=" >> $GITHUB_ENV
          exit 0
        fi
        echo "NEEDS_RESTART=false" >> $GITHUB_ENV

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add "$FILE"
        git commit -m "chore: update ${CONTAINER_NAME} image to ${TAG}"

    - name: Push branch and create PR in GitOps repo
      if: ${{ env.SKIP == 'false' && env.NEEDS_RESTART != 'true' }}
      shell: bash
      working-directory: gitops-repo
      env:
        TAG: ${{ env.DEPLOY_TAG }}
        TARGET_ENV: ${{ env.TARGET_ENV }}
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        set -euo pipefail
        ERRFILE="$GITHUB_WORKSPACE/action_error.txt"
        trap 'rc=$?; echo "ERROR creando PR/push - exit code $rc" >> "$ERRFILE"; exit $rc' ERR

        owner_repo="${{ env.GITOPS_REPO }}"
        BASE="${{ inputs.base_branch }}"
        IMAGE="${{ inputs.image_name }}"

        BRANCH="deploy/${TARGET_ENV}/${IMAGE}-${TAG}"
        PR_TITLE="${{ inputs.pr_title }} (${TARGET_ENV})"
        
        PR_BODY=$(cat <<EOF
        Actualización automática solicitada desde comentario:

        \`\`\`
        ${{ github.event.comment.body || '' }}
        \`\`\`

        - Contenedor: ${IMAGE}
        - Tag nuevo: ${TAG}
        - Entorno: ${TARGET_ENV}
        EOF
        )

        git fetch origin "$BASE" --depth=50 || true
        git checkout -B "$BRANCH"
        git push --force-with-lease origin "$BRANCH"

        echo "Creando PR..."
        pr_url=$(gh pr create \
          --repo "$owner_repo" \
          --base "$BASE" \
          --head "$BRANCH" \
          --title "$PR_TITLE" \
          --body "$PR_BODY" 2>&1 | tee /dev/stderr | grep -oE 'https://github.com/[^[:space:]]+' || true)

        if [ -z "$pr_url" ]; then
          echo "La creación de la PR falló" | tee -a "$ERRFILE"
          exit 1
        fi

        echo "GITOPS_PR_URL=$pr_url" >> $GITHUB_ENV
        echo "PR creada: $pr_url"
        
        echo "Configurando auto-merge..."
        if gh pr merge "$pr_url" --auto --merge --delete-branch 2>&1; then
          echo "Auto-merge configurado. La PR se mergeará automáticamente cuando pasen los checks requeridos."
        else
          echo "Advertencia: No se pudo configurar auto-merge (puede que no esté habilitado en el repo o que la PR ya esté lista para merge)." | tee -a "$ERRFILE"
          echo "Intentando merge directo..."
          if gh pr merge "$pr_url" --merge --delete-branch 2>&1; then
            echo "PR mergeada exitosamente."
          else
            echo "No se pudo hacer merge. Revisa manualmente: $pr_url" | tee -a "$ERRFILE"
          fi
        fi

    - name: Get GKE credentials (Staging)
      if: ${{ env.SKIP == 'false' && env.NEEDS_RESTART == 'true' && env.TARGET_ENV == 'staging' }}
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ inputs.staging_cluster_name }}
        location: ${{ inputs.staging_cluster_location }}
        project_id: ${{ inputs.project_id }}

    - name: Get GKE credentials (Prod)
      if: ${{ env.SKIP == 'false' && env.NEEDS_RESTART == 'true' && env.TARGET_ENV == 'prod' }}
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ inputs.prod_cluster_name }}
        location: ${{ inputs.prod_cluster_location }}
        project_id: ${{ inputs.project_id }}

    - name: Restart Deployment
      if: ${{ env.SKIP == 'false' && env.NEEDS_RESTART == 'true' }}
      shell: bash
      env:
        DEPLOYMENT_NAME: ${{ inputs.deployment_name || inputs.image_name }}
        K8S_NAMESPACE: ${{ inputs.namespace }}
      run: |
        set -euo pipefail
        echo "Reiniciando deployment '$DEPLOYMENT_NAME' en namespace '$K8S_NAMESPACE'..."
        kubectl rollout restart deployment/"$DEPLOYMENT_NAME" -n "$K8S_NAMESPACE"
        kubectl rollout status deployment/"$DEPLOYMENT_NAME" -n "$K8S_NAMESPACE"
        echo "RESTART_SUCCESS=true" >> $GITHUB_ENV

    - name: Report result back to source PR
      if: always() && env.SKIP == 'false'
      uses: actions/github-script@v7
      env:
        COMMENT_TOKEN: ${{ env.COMMENT_TOKEN }}
        ERRFILE: ${{ github.workspace }}/action_error.txt
        GITOPS_PR_URL: ${{ env.GITOPS_PR_URL }}
        DEPLOY_TAG: ${{ env.DEPLOY_TAG }}
        TARGET_ENV: ${{ env.TARGET_ENV }}
        NEEDS_RESTART: ${{ env.NEEDS_RESTART }}
        RESTART_SUCCESS: ${{ env.RESTART_SUCCESS }}
      with:
        github-token: ${{ env.COMMENT_TOKEN }}
        script: |
          const fs = require('fs');
          const commentBody = context.payload.comment?.body || '';
          
          if (/^[:white_check_mark:]|^[:x:]|^Imagen actualizada|^No se pudo actualizar/i.test(commentBody)) {
            core.info('El comentario parece ser una respuesta automática. No se publicará respuesta para evitar loops.');
            return;
          }
          
          const errFile = process.env.ERRFILE;
          const hasError = fs.existsSync(errFile) && fs.readFileSync(errFile, 'utf8').trim().length > 0;
          const prUrl = process.env.GITOPS_PR_URL || '';
          const deployTag = process.env.DEPLOY_TAG || '(tag no disponible)';
          const targetEnv = process.env.TARGET_ENV || '(entorno no disponible)';
          let body = '';
          if (hasError) {
            body = ':x: El despliegue del tag "' + deployTag + '" hacia "' + targetEnv + '" falló.\n\n```\n' +
              fs.readFileSync(errFile, 'utf8') + '\n```\n';
            if (prUrl) body += 'Se alcanzó a crear la PR en GitOps: ' + prUrl + '\n';
          } else if (prUrl) {
            body = ':white_check_mark: Tag "' + deployTag + '" desplegado en "' + targetEnv + '".\n' +
              'PR en GitOps: ' + prUrl + '\n';
          } else if (process.env.NEEDS_RESTART === 'true') {
             if (process.env.RESTART_SUCCESS === 'true') {
                body = ':white_check_mark: Tag "' + deployTag + '" ya existía en "' + targetEnv + '".\n' +
                       'Se ha reiniciado el deployment exitosamente para aplicar cambios.';
             } else {
                body = ':x: Tag "' + deployTag + '" ya existía, pero falló el reinicio del deployment.\n' +
                       'Revisa los logs de la acción para más detalles.';
             }
          } else {
            body = ':white_check_mark: Tag "' + deployTag + '" ya estaba aplicado en "' + targetEnv + '"; no se creó PR ni se reinició.\n';
          }

          const issueNumber = context.issue?.number ||
            context.payload?.issue?.number ||
            context.payload?.pull_request?.number;
          if (!issueNumber) {
            core.info('No se encontró número de PR/issue para comentar.');
            return;
          }

          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
            body
          });

