name: Deploy GitOps Image
description: >
  Actualiza el tag de una imagen en el repo de GitOps (staging o prod) leyendo el
  comando `deploy -t <tag> -e <env>` desde un comentario de PR y sube los cambios
  al repositorio GitOps mediante una PR automática.
inputs:
  gitops_repo:
    description: 'Repo GitOps destino en formato owner/repo o URL (ej: Automya/gitops).'
    required: true
  staging_manifest_path:
    description: 'Ruta del manifiesto Kubernetes para staging dentro del repo GitOps.'
    required: true
  prod_manifest_path:
    description: 'Ruta del manifiesto Kubernetes para producción dentro del repo GitOps.'
    required: true
  image_name:
    description: 'Nombre del contenedor (.spec.template.spec.containers[].name) a modificar.'
    required: true
  github_token:
    description: 'Token con permisos write en el repo GitOps (PAT o GITHUB_TOKEN elevado).'
    required: true
  source_repo_token:
    description: 'Token para comentar en la PR origen (opcional, default usa github_token).'
    required: false
    default: ''
  base_branch:
    description: 'Rama base en el repo GitOps (main por defecto).'
    required: false
    default: 'main'
  pr_title:
    description: 'Título base de la PR que se creará en el repo GitOps.'
    required: false
    default: 'chore: update image tag'
  staging_cluster_name:
    description: 'Staging GKE Cluster Name'
    required: true
  prod_cluster_name:
    description: 'Prod GKE Cluster Name'
    required: true
  staging_cluster_location:
    description: 'Staging GKE Cluster Location'
    required: true
  prod_cluster_location:
    description: 'Prod GKE Cluster Location'
    required: true
  project_id:
    description: 'GCP Project ID (shared for both clusters)'
    required: true
  deployment_name:
    description: 'K8s Deployment name to restart (defaults to image_name if not set)'
    required: false
  namespace:
    description: 'K8s Namespace (default: default)'
    required: false
    default: 'default'
  google_chat_webhook:
    description: 'Webhook URL para notificaciones a Google Chat (opcional).'
    required: false
runs:
  using: composite
  steps:
    - name: Initialize Context
      uses: Automya/CI-CD-template/internal/deploy-context-init@main
      with:
        source_repo_token: ${{ inputs.source_repo_token }}
        github_token: ${{ inputs.github_token }}

    - name: Parse Deploy Command
      id: parse
      uses: Automya/CI-CD-template/internal/parse-comment@main
      with:
        comment_body: ${{ github.event.comment.body }}
        command_prefix: "deploy"

    - name: Validate & Prepare Context
      id: ctx
      uses: Automya/CI-CD-template/internal/deploy-validate-context@main
      with:
        tag: ${{ steps.parse.outputs.tag }}
        env_raw: ${{ steps.parse.outputs.env }}
        is_valid_command: ${{ steps.parse.outputs.is_valid }}
        error_msg: ${{ steps.parse.outputs.error_msg }}

    - name: Notify Start Deployment
      if: ${{ steps.ctx.outputs.skip == 'false' && steps.ctx.outputs.stop_execution == 'false' }}
      uses: Automya/CI-CD-template/internal/notify@main
      with:
        github_token: ${{ env.COMMENT_TOKEN }}
        pr_number: ${{ github.event.issue.number || github.event.pull_request.number }}
        webhook_url: ${{ inputs.google_chat_webhook }}
        pr_message: "🚀 Iniciando Despliegue de ${{ inputs.image_name }} (${{ steps.ctx.outputs.deploy_tag }}) a ${{ steps.ctx.outputs.target_env }}..."
        chat_message: |
          🚀 **Iniciando Despliegue**
          - **Imagen:** `${{ inputs.image_name }}`
          - **Tag:** `${{ steps.ctx.outputs.deploy_tag }}`
          - **Entorno:** `${{ steps.ctx.outputs.target_env }}`
          - [Ver Logs del Action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          ⏳ Procesando...

    - name: Normalize GitOps repository
      if: ${{ steps.ctx.outputs.skip == 'false' && steps.ctx.outputs.stop_execution == 'false' }}
      id: norm
      uses: Automya/CI-CD-template/internal/util-normalize-repo@main
      with:
        repo_input: ${{ inputs.gitops_repo }}

    - name: Select Manifest Path
      if: ${{ steps.ctx.outputs.skip == 'false' && steps.ctx.outputs.stop_execution == 'false' }}
      id: manifest
      uses: Automya/CI-CD-template/internal/deploy-select-manifest@main
      with:
        target_env: ${{ steps.ctx.outputs.target_env }}
        staging_path: ${{ inputs.staging_manifest_path }}
        prod_path: ${{ inputs.prod_manifest_path }}

    - name: GitOps Update & PR
      if: ${{ steps.ctx.outputs.skip == 'false' && steps.ctx.outputs.stop_execution == 'false' }}
      id: gitops
      uses: Automya/CI-CD-template/internal/gitops-pr@main
      with:
        gitops_repo: ${{ steps.norm.outputs.repo_normalized }}
        gitops_token: ${{ inputs.github_token }}
        manifest_path: ${{ steps.manifest.outputs.manifest_path }}
        container_name: ${{ inputs.image_name }}
        image_tag: ${{ steps.ctx.outputs.deploy_tag }}
        target_env: ${{ steps.ctx.outputs.target_env }}
        base_branch: ${{ inputs.base_branch }}

    - name: Get GKE credentials (Staging)
      if: ${{ steps.ctx.outputs.skip == 'false' && steps.ctx.outputs.stop_execution == 'false' && steps.gitops.outputs.needs_restart == 'true' && steps.ctx.outputs.target_env == 'staging' }}
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ inputs.staging_cluster_name }}
        location: ${{ inputs.staging_cluster_location }}
        project_id: ${{ inputs.project_id }}

    - name: Get GKE credentials (Prod)
      if: ${{ steps.ctx.outputs.skip == 'false' && steps.ctx.outputs.stop_execution == 'false' && steps.gitops.outputs.needs_restart == 'true' && steps.ctx.outputs.target_env == 'prod' }}
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ inputs.prod_cluster_name }}
        location: ${{ inputs.prod_cluster_location }}
        project_id: ${{ inputs.project_id }}

    - name: Restart Deployment
      if: ${{ steps.ctx.outputs.skip == 'false' && steps.ctx.outputs.stop_execution == 'false' && steps.gitops.outputs.needs_restart == 'true' }}
      id: restart
      uses: Automya/CI-CD-template/internal/k8s-rollout-restart@main
      with:
        deployment_name: ${{ inputs.deployment_name || inputs.image_name }}
        namespace: ${{ inputs.namespace }}

    - name: Generate Report Message
      id: report
      if: always() && steps.ctx.outputs.skip == 'false'
      uses: Automya/CI-CD-template/internal/deploy-report@main
      with:
        job_status: ${{ job.status }}
        gitops_pr_url: ${{ steps.gitops.outputs.pr_url }}
        deploy_tag: ${{ steps.ctx.outputs.deploy_tag }}
        target_env: ${{ steps.ctx.outputs.target_env }}
        needs_restart: ${{ steps.gitops.outputs.needs_restart }}
        restart_success: ${{ steps.restart.outputs.success }}
        error_file_path: ${{ github.workspace }}/action_error.txt

    - name: Notify Final Result
      if: always() && steps.ctx.outputs.skip == 'false'
      uses: Automya/CI-CD-template/internal/notify@main
      with:
        github_token: ${{ env.COMMENT_TOKEN }}
        pr_number: ${{ github.event.issue.number || github.event.pull_request.number }}
        webhook_url: ${{ inputs.google_chat_webhook }}
        pr_message: ${{ steps.report.outputs.message }}
