name: "build-image-docker-gcp"
description: "Composite action: construye y sube una imagen a Artifact Registry (GCP). Lee variables del entorno del job consumidor."
runs:
  using: "composite"
  steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Authenticate to Google Cloud (usa GCP_SA_KEY pasado como env)
      shell: bash
      run: |
        if [ -z "${GCP_SA_KEY}" ]; then
          echo "GCP_SA_KEY no está definido. Pasa el secret como env en el step que usa la action."
          exit 1
        fi
        echo "${GCP_SA_KEY}" > /tmp/gcp_key.json
        gcloud auth activate-service-account --key-file=/tmp/gcp_key.json
        if [ -n "${PROJECT_ID}" ]; then
          gcloud config set project "${PROJECT_ID}"
        fi

    - name: Set image tag
      id: image-tag
      shell: bash
      run: |
        if [[ "$GITHUB_REF" == refs/tags/* ]]; then
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          echo "TAG=MAIN" >> $GITHUB_OUTPUT
        fi

    - name: Configure Docker for Artifact Registry
      shell: bash
      run: |
        if [ -z "${GCP_REGION}" ]; then
          echo "REGION no está definido."
          exit 1
        fi
        gcloud auth configure-docker ${GCP_REGION}-docker.pkg.dev --quiet

    - name: Build Docker image
      shell: bash
      run: |
        if [ -z "${PROJECT_ID}" ] || [ -z "${REPOSITORY}" ] || [ -z "${IMAGE_NAME}" ]; then
          echo "PROJECT_ID, REPOSITORY y IMAGE_NAME deben estar definidos en el entorno del job."
          exit 1
        fi
        docker build \
          --build-arg MAVEN_USERNAME=${MAVEN_USERNAME} \
          --build-arg MAVEN_PASSWORD=${MAVEN_PASSWORD} \
          -t ${GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${{ steps.image-tag.outputs.TAG }} .

    - name: Push Docker image
      shell: bash
      run: |
        docker push ${GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${{ steps.image-tag.outputs.TAG }}