name: "GCP Docker Build & Push with PR feedback"
description: "Builds and pushes Docker images to GCP Artifact Registry using Workload Identity Federation and reports back to PR comments in PRs."

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Limpia variables credenciales para que GCloud nunca busque un archivo de credencial
    - name: Clean GCP credential env vars
      shell: bash
      run: |
        unset GOOGLE_APPLICATION_CREDENTIALS
        unset CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
        unset GOOGLE_GHA_CREDS_PATH
        unset GCP_SA_KEY
        export GOOGLE_APPLICATION_CREDENTIALS=""
        export CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=""
        export GOOGLE_GHA_CREDS_PATH=""
        export GCP_SA_KEY=""

    # Instala gcloud sin login, y sobreescribe env solo para este step
    - name: Install gcloud SDK
      uses: google-github-actions/setup-gcloud@v2
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ""
        CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: ""
        GOOGLE_GHA_CREDS_PATH: ""
        GCP_SA_KEY: ""

    - name: Configure Docker for GCP
      shell: bash
      run: |
        gcloud auth configure-docker "$GCP_REGION-docker.pkg.dev" --quiet

    # Determina correctamente el nombre de la rama real y el tag para Docker
    - name: Determine build context
      id: context
      shell: bash
      run: |
        set -e
        EVENT="${{ github.event_name }}"
        TAG=""
        BRANCH=""
        SAFE_BRANCH=""
        COMMENT_BODY="${{ github.event.comment.body }}"
        PR_NUMBER=$(jq -r '.issue.number // empty' < "$GITHUB_EVENT_PATH")
        JOB_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

        comment_pr() {
          MSG="$1"
          if [[ -n "$PR_NUMBER" ]]; then
            curl -s -H "Authorization: token $GH_TOKEN" \
              -X POST \
              -d "{\"body\":\"$MSG\"}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments" > /dev/null
          fi
        }

        if [[ "$EVENT" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
          TAG="MAIN"
          BRANCH="main"

        elif [[ "$EVENT" == "issue_comment" && "$(jq -r '.issue.pull_request // empty' < "$GITHUB_EVENT_PATH")" != "" ]]; then
          if [[ "$COMMENT_BODY" =~ ^build($|\s) ]]; then
            [[ "$COMMENT_BODY" =~ -t[[:space:]]+([^\ ]+) ]] && TAG="${BASH_REMATCH[1]}" || TAG=""
            [[ "$COMMENT_BODY" =~ -b[[:space:]]+([^\ ]+) ]] && BRANCH="${BASH_REMATCH[1]}" || BRANCH=""
          else
            exit 0
          fi

          if [[ -z "$BRANCH" ]]; then
            PR_URL=$(jq -r '.issue.pull_request.url // empty' < "$GITHUB_EVENT_PATH")
            BRANCH=$(curl -s -H "Authorization: token $GH_TOKEN" "$PR_URL" | jq -r .head.ref)
          fi

          SAFE_BRANCH=$(echo "$BRANCH" | tr '/' '-')

          is_semver() { [[ "$1" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; }

          # El TAG siempre será el SAFE_BRANCH si no está explícito
          if [[ -z "$TAG" ]]; then
            TAG="$SAFE_BRANCH"
          else
            if [[ "$BRANCH" == "main" ]]; then
              if ! is_semver "$TAG"; then
                comment_pr "❌ Error: Solo se permiten tags semánticos (v1.2.3) en main. [Ver logs]($JOB_URL)"
                exit 1
              fi
            else
              if is_semver "$TAG"; then
                comment_pr "❌ Error: Tags semánticos solo están permitidos en main. [Ver logs]($JOB_URL)"
                exit 1
              fi
            fi
          fi

          comment_pr "🚀 Build iniciado para la rama ${BRANCH} con tag ${TAG}. [Ver ejecución]($JOB_URL)"

        elif [[ "$EVENT" == "release" && "${GITHUB_REF}" =~ ^refs/tags/v ]]; then
          TAG="${{ github.event.release.tag_name }}"
          BRANCH="${{ github.event.release.target_commitish }}"
          if [[ "$BRANCH" != "main" ]]; then
            comment_pr "❌ Error: Release con tag ${TAG} no apunta a main. [Ver logs]($JOB_URL)"
            exit 1
          fi
        else
          exit 0
        fi

        # Para checkout y trabajo, usar la rama real (BRANCH), para el tag docker el "SAFE_BRANCH"
        echo "branch=$BRANCH" >> "$GITHUB_OUTPUT"
        echo "safe_branch=$SAFE_BRANCH" >> "$GITHUB_OUTPUT"
        echo "tag=$TAG" >> "$GITHUB_OUTPUT"
        echo "job_url=$JOB_URL" >> "$GITHUB_OUTPUT"

    - name: Checkout branch
      if: steps.context.outputs.branch != ''
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.context.outputs.branch }}

    - name: Build and push image
      if: steps.context.outputs.tag != ''
      id: build
      shell: bash
      run: |
        TAG="${{ steps.context.outputs.tag }}"
        FULL_IMAGE="$GCP_REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$TAG"
        docker build \
          --build-arg MAVEN_USERNAME="${MAVEN_USERNAME}" \
          --build-arg MAVEN_PASSWORD="${MAVEN_PASSWORD}" \
          -t "$FULL_IMAGE" .
        docker push "$FULL_IMAGE"
        echo "status=success" >> "$GITHUB_OUTPUT"

    - name: Comment build result on PR
      if: github.event_name == 'issue_comment' && steps.context.outputs.tag != ''
      shell: bash
      run: |
        PR_NUMBER=$(jq -r '.issue.number // empty' < "$GITHUB_EVENT_PATH")
        JOB_URL="${{ steps.context.outputs.job_url }}"
        STATUS="${{ steps.build.outputs.status }}"
        TAG="${{ steps.context.outputs.tag }}"
        IMAGE="$GCP_REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$TAG"

        comment() {
          MSG="$1"
          curl -s -H "Authorization: token $GH_TOKEN" \
            -X POST \
            -d "{\"body\":\"$MSG\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments" > /dev/null
        }

        case "$STATUS" in
          "build_failed")
            comment "❌ Error: Falló la construcción de la imagen ${IMAGE}. [Ver logs del job]($JOB_URL)"
            ;;
          "push_failed")
            comment "❌ Error: Falló el push de la imagen ${IMAGE}. [Ver logs del job]($JOB_URL)"
            ;;
          "success")
            comment "🎉 Éxito: Imagen ${IMAGE} subida correctamente. [Ver ejecución completa]($JOB_URL)"
            ;;
        esac