name: "GCP Docker Build & Push with PR feedback"
description: "Builds and pushes Docker images to GCP Artifact Registry using Workload Identity Federation and reports back to PR comments in PRs."
inputs:
  gitops_repo:
    description: "Repo GitOps destino en formato owner/repo (ej: Automya/gitops)."
    required: false
  prod_manifest_path:
    description: "Ruta del manifiesto Kubernetes para producción dentro del repo GitOps."
    required: false
  gitops_token:
    description: "Token con permisos write en el repo GitOps."
    required: false
  container_name:
    description: "Nombre del contenedor a actualizar en el manifiesto (opcional, usa IMAGE_NAME si no se define)."
    required: false
  google_chat_webhook:
    description: "Webhook URL para notificaciones a Google Chat (opcional)."
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout CI-CD-template
      uses: actions/checkout@v4
      with:
        repository: ${{ github.action_repository }}
        ref: ${{ github.action_ref }}
        path: .github/actions-template

    - name: Notify Start
      if: github.event_name == 'issue_comment'
      uses: .github/actions-template/internal/notify
      with:
        github_token: ${{ env.GH_TOKEN }}
        pr_number: ${{ github.event.issue.number }}
        webhook_url: ${{ inputs.google_chat_webhook }}
        pr_message: "🚀 Iniciando Build, espere por favor..."
        chat_message: |
          🚀 **Iniciando Build**
          - **Repo:** ${{ github.repository }}
          - **PR:** #${{ github.event.issue.number }}
          - [Ver Logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          ⏳ Iniciando...

    - name: Parse Comment
      if: github.event_name == 'issue_comment'
      id: parse
      uses: .github/actions-template/internal/parse-comment
      with:
        comment_body: ${{ github.event.comment.body }}
        command_prefix: "build"

    - name: Determine Context
      id: ctx
      uses: .github/actions-template/internal/build-context-determine
      with:
        event_name: ${{ github.event_name }}
        is_valid_command: ${{ steps.parse.outputs.is_valid }}
        parsed_branch: ${{ steps.parse.outputs.branch }}
        parsed_tag: ${{ steps.parse.outputs.tag }}
        github_token: ${{ env.GH_TOKEN }}

    - name: Checkout code
      if: steps.ctx.outputs.branch != ''
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.ctx.outputs.branch }}

    - name: Setup GCP & Docker
      if: steps.ctx.outputs.status == ''
      uses: .github/actions-template/internal/setup-gcp
      with:
        region: ${{ env.GCP_REGION }}

    - name: Build and Push
      if: steps.ctx.outputs.status == ''
      id: build
      uses: .github/actions-template/internal/docker-build-push
      with:
        image_full_name: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ steps.ctx.outputs.tag }}

    - name: GitOps Update (Release only)
      if: github.event_name == 'release' && steps.build.outputs.status == 'success'
      uses: .github/actions-template/internal/gitops-pr
      with:
        gitops_repo: ${{ inputs.gitops_repo }}
        gitops_token: ${{ inputs.gitops_token }}
        manifest_path: ${{ inputs.prod_manifest_path }}
        container_name: ${{ inputs.container_name || env.IMAGE_NAME }}
        image_tag: ${{ steps.ctx.outputs.tag }}
        target_env: "prod"

    - name: Prepare Report
      if: github.event_name == 'issue_comment'
      id: report
      uses: .github/actions-template/internal/build-report-message
      with:
        status: ${{ steps.ctx.outputs.status || steps.build.outputs.status }}
        job_url: ${{ steps.ctx.outputs.job_url }}
        image_full_name: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ steps.ctx.outputs.tag }}

    - name: Notify Result
      if: github.event_name == 'issue_comment'
      uses: .github/actions-template/internal/notify
      with:
        github_token: ${{ env.GH_TOKEN }}
        pr_number: ${{ github.event.issue.number }}
        webhook_url: ${{ inputs.google_chat_webhook }}
        pr_message: ${{ steps.report.outputs.pr_message }}
        chat_message: ${{ steps.report.outputs.chat_message }}
