name: 'Trivy SAST Scan'
description: 'Run Trivy Vulnerability Scanner'
inputs:
  trivyignore-file:
    description: 'Path to the .trivyignore file (relative to repo root)'
    required: false
    default: '.trivyignore'

runs:
  using: "composite"
  steps:
    - name: Generate POMs for Scanning
      shell: bash
      run: |
        if [ -f "./gradlew" ]; then
             echo "Gradle project detected. Generating POMs for accurate scanning..."
             
             # Crear script de inicialización para inyectar plugin maven-publish
             # Usamos printf para evitar problemas de indentación con EOF en YAML
             printf "allprojects {\n    plugins.withId('java') {\n        apply plugin: 'maven-publish'\n        publishing {\n            publications {\n                maven(MavenPublication) {\n                    from components.java\n                }\n            }\n        }\n    }\n}\n" > init-trivy.gradle
             
             chmod +x ./gradlew
             # Generar los POMs. Usamos || true para no fallar el build si algún módulo da error.
             ./gradlew generatePomFileForMavenPublication --init-script init-trivy.gradle || echo "Warning: POM generation had issues"
             
             echo "Generated POM files:"
             find . -name "pom-default.xml" || echo "No POMs found"
        fi


    - name: Check Trivy Ignore Expiration
      shell: bash
      run: |
        IGNORE_FILE="${{ inputs.trivyignore-file }}"
        
        if [ ! -f "$IGNORE_FILE" ]; then
          echo "No ignore file found at $IGNORE_FILE"
          exit 0
        fi

        CURRENT_DATE=$(date +%Y-%m-%d)
        TEMP_FILE=$(mktemp)
        SKIP_NEXT=0

        echo "Checking expiration dates in $IGNORE_FILE..."

        while IFS= read -r line || [ -n "$line" ]; do
          # Si debemos saltar esta línea (porque es el CVE de un comentario expirado)
          if [ "$SKIP_NEXT" -eq 1 ]; then
            echo "   -> Removing expired CVE: $line"
            SKIP_NEXT=0
            continue
          fi

          # Buscar patrón "# exp: YYYY-MM-DD"
          if [[ "$line" =~ \#\ *exp:\ *([0-9]{4}-[0-9]{2}-[0-9]{2}) ]]; then
            EXP_DATE=${BASH_REMATCH[1]}
            if [[ "$CURRENT_DATE" > "$EXP_DATE" ]]; then
              echo "⚠️ Expiration date ($EXP_DATE) passed. Removing next CVE."
              SKIP_NEXT=1
              continue # No escribimos la línea de comentario expirada
            fi
          fi
          
          echo "$line" >> "$TEMP_FILE"
        done < "$IGNORE_FILE"

        mv "$TEMP_FILE" "$IGNORE_FILE"
        echo "Processed ignore file:"
        cat "$IGNORE_FILE"

    - name: Download Trivy HTML Template
      shell: bash
      run: |
        curl -sL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -o html.tpl

    - name: Generate Trivy Report
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'template'
        template: '@html.tpl'
        output: 'trivy-report.html'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
        trivyignores: ${{ inputs.trivyignore-file }}
        exit-code: '0'

    - name: Upload Trivy Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: trivy-report
        path: trivy-report.html

    - name: Check Vulnerabilities (Console)
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
        trivyignores: ${{ inputs.trivyignore-file }}
