name: 'Trivy SAST Scan'
description: 'Run Trivy Vulnerability Scanner'
inputs:
  trivyignore-file:
    description: 'Path to the .trivyignore file (relative to repo root)'
    required: false
    default: '.trivyignore'

runs:
  using: "composite"
  steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
        trivyignores: ${{ inputs.trivyignore-file }}
