name: 'Trivy SAST Scan'
description: 'Run Trivy Vulnerability Scanner using SBOM'
inputs:
  trivyignore-file:
    description: 'Path to the .trivyignore file (relative to repo root)'
    required: false
    default: '.trivyignore'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js for cdxgen
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install cdxgen
      shell: bash
      run: npm install -g @cyclonedx/cdxgen

    - name: Generate SBOM (CycloneDX)
      shell: bash
      run: |
        echo "Generating SBOM for Gradle project..."
        # cdxgen detecta automáticamente gradle si ve archivos build.gradle
        # --resolve-class es util para java
        cdxgen -t gradle -o bom.json --recurse
        
        if [ -f "bom.json" ]; then
          echo "SBOM generated successfully. Size:"
          ls -lh bom.json
        else
          echo "Failed to generate SBOM. Checking debug logs..."
          exit 1
        fi

    - name: Check Trivy Ignore Expiration
      shell: bash
      run: |
        IGNORE_FILE="${{ inputs.trivyignore-file }}"
        
        if [ ! -f "$IGNORE_FILE" ]; then
          echo "No ignore file found at $IGNORE_FILE"
          exit 0
        fi

        CURRENT_DATE=$(date +%Y-%m-%d)
        TEMP_FILE=$(mktemp)
        SKIP_NEXT=0

        echo "Checking expiration dates in $IGNORE_FILE..."

        while IFS= read -r line || [ -n "$line" ]; do
          if [ "$SKIP_NEXT" -eq 1 ]; then
            echo "   -> Removing expired CVE: $line"
            SKIP_NEXT=0
            continue
          fi

          if [[ "$line" =~ \#\ *exp:\ *([0-9]{4}-[0-9]{2}-[0-9]{2}) ]]; then
            EXP_DATE=${BASH_REMATCH[1]}
            if [[ "$CURRENT_DATE" > "$EXP_DATE" ]]; then
              echo "⚠️ Expiration date ($EXP_DATE) passed. Removing next CVE."
              SKIP_NEXT=1
              continue
            fi
          fi
          
          echo "$line" >> "$TEMP_FILE"
        done < "$IGNORE_FILE"

        mv "$TEMP_FILE" "$IGNORE_FILE"
        echo "Processed ignore file:"
        cat "$IGNORE_FILE"

    - name: Download Trivy HTML Template
      shell: bash
      run: |
        curl -sL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -o html.tpl

    - name: Generate Trivy Report (SBOM)
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'sbom'
        scan-ref: 'bom.json'
        format: 'template'
        template: '@html.tpl'
        output: 'trivy-report.html'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
        trivyignores: ${{ inputs.trivyignore-file }}
        exit-code: '0'

    - name: Upload Trivy Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: trivy-report
        path: trivy-report.html

    - name: Check Vulnerabilities (Console SBOM)
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'sbom'
        scan-ref: 'bom.json'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
        trivyignores: ${{ inputs.trivyignore-file }}
