name: "Initialize Confluence Sync Context"
description: "Initializes environment variables and error tracking file for Confluence sync workflow"

runs:
  using: "composite"
  steps:
    - name: Initialize
      shell: bash
      run: |
        set -euo pipefail

        echo "Initializing Confluence sync context..."

        # Create empty error file for tracking sync errors
        : > "$GITHUB_WORKSPACE/action_error.txt"

        # Set environment variables
        echo "SKIP=false" >> $GITHUB_ENV
        echo "CONFLUENCE_SYNC_STATUS=pending" >> $GITHUB_ENV

        echo "Context initialized successfully"
