name: "Detect Documentation Changes"
description: "Detects which Markdown files have been changed or deleted between commits"

inputs:
  docs_folder:
    description: "Path to documentation folder"
    required: true
  base_ref:
    description: "Base git reference for comparison (e.g., HEAD~1)"
    required: true
  head_ref:
    description: "Head git reference (e.g., HEAD or commit SHA)"
    required: true

outputs:
  changed_files:
    description: "Space-separated list of changed .md files"
    value: ${{ steps.detect.outputs.changed_files }}
  deleted_files:
    description: "Space-separated list of deleted .md files"
    value: ${{ steps.detect.outputs.deleted_files }}
  has_changes:
    description: "Boolean indicating if any changes were detected"
    value: ${{ steps.detect.outputs.has_changes }}

runs:
  using: "composite"
  steps:
    - name: Detect Changes
      id: detect
      shell: bash
      env:
        DOCS_FOLDER: ${{ inputs.docs_folder }}
        BASE_REF: ${{ inputs.base_ref }}
        HEAD_REF: ${{ inputs.head_ref }}
      run: |
        set -euo pipefail

        echo "Detecting changes in documentation folder: $DOCS_FOLDER"
        echo "Comparing $BASE_REF vs $HEAD_REF"

        # Determine the correct path pattern for git diff
        if [ "$DOCS_FOLDER" = "." ] || [ "$DOCS_FOLDER" = "./" ]; then
          # When syncing from root, search for all .md files recursively
          # Use '*.md' for root level and find additional files with grep
          echo "Searching for all .md files in repository (excluding .github)"

          # Get all changed .md files, then filter out .github
          CHANGED=$(git diff --name-only --diff-filter=ACMR "$BASE_REF" "$HEAD_REF" 2>/dev/null | grep '\.md$' | grep -v '^\.github/' | tr '\n' ' ' || echo "")
          DELETED=$(git diff --name-only --diff-filter=D "$BASE_REF" "$HEAD_REF" 2>/dev/null | grep '\.md$' | grep -v '^\.github/' | tr '\n' ' ' || echo "")
        else
          # When syncing from specific folder, use folder/**/*.md pattern
          echo "Using path pattern: ${DOCS_FOLDER}/**/*.md"

          CHANGED=$(git diff --name-only --diff-filter=ACMR "$BASE_REF" "$HEAD_REF" -- "${DOCS_FOLDER}/**/*.md" 2>/dev/null | tr '\n' ' ' || echo "")
          DELETED=$(git diff --name-only --diff-filter=D "$BASE_REF" "$HEAD_REF" -- "${DOCS_FOLDER}/**/*.md" 2>/dev/null | tr '\n' ' ' || echo "")
        fi

        # Set outputs
        echo "changed_files=$CHANGED" >> "$GITHUB_OUTPUT"
        echo "deleted_files=$DELETED" >> "$GITHUB_OUTPUT"

        # Determine if there are any changes
        if [ -n "$CHANGED" ] || [ -n "$DELETED" ]; then
          echo "has_changes=true" >> "$GITHUB_OUTPUT"
          echo "✓ Changes detected:"
          if [ -n "$CHANGED" ]; then
            echo "  Changed/Added files: $CHANGED"
          fi
          if [ -n "$DELETED" ]; then
            echo "  Deleted files: $DELETED"
          fi
        else
          echo "has_changes=false" >> "$GITHUB_OUTPUT"
          echo "✓ No changes detected in documentation files"
        fi
