name: publish-java-artifacts
description: "Composite action: sube artifacts a Artifacts (repo central)."

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: ./internal/setup-java-gradle
      
    - name: Publish with Gradle
      run: ./gradlew --no-daemon publish -x test
      shell: bash
