name: Restart Deployment on push to main (GKE with service account JSON)

runs:
    using: "composite"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP using service account JSON
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials (configure kubectl)
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_LOCATION }} # zone or region
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Verify kubectl context
        run: |
          kubectl config current-context
          kubectl version --client
          kubectl get nodes --no-headers || true

      - name: Restart deployment
        env:
          DEPLOYMENT_NAME: ${{ secrets.DEPLOYMENT_NAME }}
          K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE }}
        run: |
          if [ -z "$DEPLOYMENT_NAME" ]; then
            echo "ERROR: DEPLOYMENT_NAME secret is required"
            exit 1
          fi
          NS="${K8S_NAMESPACE:-default}"
          echo "Restarting deployment '$DEPLOYMENT_NAME' in namespace '$NS'"
          kubectl rollout restart deployment/"$DEPLOYMENT_NAME" -n "$NS"
          kubectl rollout status deployment/"$DEPLOYMENT_NAME" -n "$NS" --timeout=120s