inputs:
  credentials_json:
    description: 'Service Account JSON for GCP authentication'
    required: true
  project_id:
    description: 'GCP Project ID'
    required: true
  cluster_name:
    description: 'GKE Cluster Name'
    required: true
  cluster_location:
    description: 'GKE Cluster Location (zone or region)'
    required: true
  deployment_name:
    description: 'Kubernetes Deployment Name to restart'
    required: true
  namespace:
    description: 'Kubernetes Namespace'
    required: false
    default: 'default'

runs:
  using: "composite"
  steps:
    - name: Get GKE credentials (configure kubectl)
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ inputs.cluster_name }}
        location: ${{ inputs.cluster_location }}
        project_id: ${{ inputs.project_id }}

    - name: Verify kubectl context
      shell: bash
      run: |
        kubectl config current-context
        kubectl version --client

    - name: Restart deployment
      shell: bash
      env:
        DEPLOYMENT_NAME: ${{ inputs.deployment_name }}
        K8S_NAMESPACE: ${{ inputs.namespace }}
      run: |
        echo "Restarting deployment '$DEPLOYMENT_NAME' in namespace '$K8S_NAMESPACE'"
        kubectl rollout restart deployment/"$DEPLOYMENT_NAME" -n "$K8S_NAMESPACE"
        kubectl rollout status deployment/"$DEPLOYMENT_NAME" -n "$K8S_NAMESPACE" --timeout=120s